/* Generated by Cython 0.9.6.10.1 on Wed Jan  2 11:30:23 2008 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)   PyInt_AsLong(o)
  #define PyNumber_Index(o)    PyNumber_Int(o)
  #define PyIndex_Check(o)     PyNumber_Check(o)
#endif
#if PY_VERSION_HEX < 0x02040000
  #define METH_COEXIST 0
#endif
#ifndef WIN32
  #define __stdcall
  #define __cdecl
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>
#include "stdio.h"
#include "cblast_misc.c"


#ifdef __GNUC__
#define INLINE __inline__
#elif _WIN32
#define INLINE __inline
#else
#define INLINE 
#endif

typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n; int is_unicode;} __Pyx_StringTabEntry; /*proto*/



static int __pyx_skip_dispatch = 0;


/* Type Conversion Predeclarations */

#define __Pyx_PyBool_FromLong(b) ((b) ? (Py_INCREF(Py_True), Py_True) : (Py_INCREF(Py_False), Py_False))
static INLINE int __Pyx_PyObject_IsTrue(PyObject* x);
static INLINE PY_LONG_LONG __pyx_PyInt_AsLongLong(PyObject* x);
static INLINE unsigned PY_LONG_LONG __pyx_PyInt_AsUnsignedLongLong(PyObject* x);
static INLINE Py_ssize_t __pyx_PyIndex_AsSsize_t(PyObject* b);

#define __pyx_PyInt_AsLong(x) (PyInt_CheckExact(x) ? PyInt_AS_LONG(x) : PyInt_AsLong(x))
#define __pyx_PyFloat_AsDouble(x) (PyFloat_CheckExact(x) ? PyFloat_AS_DOUBLE(x) : PyFloat_AsDouble(x))

static INLINE unsigned char __pyx_PyInt_unsigned_char(PyObject* x);
static INLINE unsigned short __pyx_PyInt_unsigned_short(PyObject* x);
static INLINE char __pyx_PyInt_char(PyObject* x);
static INLINE short __pyx_PyInt_short(PyObject* x);
static INLINE int __pyx_PyInt_int(PyObject* x);
static INLINE long __pyx_PyInt_long(PyObject* x);
static INLINE signed char __pyx_PyInt_signed_char(PyObject* x);
static INLINE signed short __pyx_PyInt_signed_short(PyObject* x);
static INLINE signed int __pyx_PyInt_signed_int(PyObject* x);
static INLINE signed long __pyx_PyInt_signed_long(PyObject* x);
static INLINE long double __pyx_PyInt_long_double(PyObject* x);
#ifdef __GNUC__
/* Test for GCC > 2.95 */
#if __GNUC__ > 2 ||               (__GNUC__ == 2 && (__GNUC_MINOR__ > 95)) 
#define likely(x)   __builtin_expect(!!(x), 1)
#define unlikely(x) __builtin_expect(!!(x), 0)
#else /* __GNUC__ > 2 ... */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ > 2 ... */
#else /* __GNUC__ */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ */
    
static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static char __pyx_mdoc[] = "\ntake a tab-delimited blast hit and turn the relative coordinates into global,\nabsolute coordinates, the name format (columns 1, 2) must be in the\nformat: \n    chr||name||start||stop\n    01||AT2G26540||123680||124220\n";

static int __Pyx_GetStarArgs(PyObject **args, PyObject **kwds, char *kwd_list[],     Py_ssize_t nargs, PyObject **args2, PyObject **kwds2, char rqd_kwds[]); /*proto*/

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/

static int __Pyx_PrintItem(PyObject *); /*proto*/
static int __Pyx_PrintNewline(void); /*proto*/

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static PyObject *__Pyx_UnpackItem(PyObject *); /*proto*/
static int __Pyx_EndUnpack(PyObject *); /*proto*/

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from blast_misc */

static char *__pyx_v_10blast_misc_blast_format;
static PyObject *__pyx_k34;
static PyObject *__pyx_k35;
static PyObject *__pyx_k36;
static PyObject *__pyx_k37;


/* Implementation of blast_misc */

static char __pyx_k33[] = "%s\t%s\t%f\t%d\t%d\t%d\t%d\t%d\t%d\t%d\t%e\t%f\n";

static PyObject *__pyx_num_1;
static PyObject *__pyx_num_6;

static PyObject *__pyx_n_operator;
static PyObject *__pyx_n_collections;
static PyObject *__pyx_n_os;
static PyObject *__pyx_n_numpy;
static PyObject *__pyx_n_query;
static PyObject *__pyx_n_subject;
static PyObject *__pyx_n_percent_id;
static PyObject *__pyx_n_hit_length;
static PyObject *__pyx_n_n_mismatch;
static PyObject *__pyx_n_n_gaps;
static PyObject *__pyx_n_qstart;
static PyObject *__pyx_n_qstop;
static PyObject *__pyx_n_sstart;
static PyObject *__pyx_n_sstop;
static PyObject *__pyx_n_eval;
static PyObject *__pyx_n_score;
static PyObject *__pyx_n_hit_rank;
static PyObject *__pyx_n_dup;
static PyObject *__pyx_n_BLAST_NAMES;
static PyObject *__pyx_n_S8;
static PyObject *__pyx_n_f4;
static PyObject *__pyx_n_i4;
static PyObject *__pyx_n_i8;
static PyObject *__pyx_n_f8;
static PyObject *__pyx_n_b1;
static PyObject *__pyx_n_BLAST_TYPES;

/* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":57
 * 
 * 
 * def pyaddlocs(inname, outname=None):             # <<<<<<<<<<<<<< 
 *     """ take a file name and add the global locs 
 *     inplace if outname==None, or to a new file (outname).
 */

static PyObject *__pyx_pf_10blast_misc_pyaddlocs(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_10blast_misc_pyaddlocs[] = " take a file name and add the global locs \n    inplace if outname==None, or to a new file (outname).\n    ";
static PyObject *__pyx_pf_10blast_misc_pyaddlocs(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_inname = 0;
  PyObject *__pyx_v_outname = 0;
  PyObject *__pyx_r;
  int __pyx_1;
  char *__pyx_2;
  PyObject *__pyx_3 = 0;
  char *__pyx_4;
  static char *__pyx_argnames[] = {"inname","outname",0};
  __pyx_v_outname = __pyx_k34;
  if (unlikely(!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O|O", __pyx_argnames, &__pyx_v_inname, &__pyx_v_outname))) return NULL;
  Py_INCREF(__pyx_v_inname);
  Py_INCREF(__pyx_v_outname);

  /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":61
 *     inplace if outname==None, or to a new file (outname).
 *     """
 *     if outname is None:             # <<<<<<<<<<<<<< 
 *         return add_locs(inname, NULL)
 *     return add_locs(inname, outname)
 */
  __pyx_1 = (__pyx_v_outname == Py_None);
  if (__pyx_1) {

    /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":62
 *     """
 *     if outname is None:
 *         return add_locs(inname, NULL)             # <<<<<<<<<<<<<< 
 *     return add_locs(inname, outname)
 * 
 */
    __pyx_2 = PyString_AsString(__pyx_v_inname); if (unlikely((!__pyx_2) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 62; goto __pyx_L1;}
    __pyx_3 = PyInt_FromLong(add_locs(__pyx_2,NULL)); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 62; goto __pyx_L1;}
    __pyx_r = __pyx_3;
    __pyx_3 = 0;
    goto __pyx_L0;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":63
 *     if outname is None:
 *         return add_locs(inname, NULL)
 *     return add_locs(inname, outname)             # <<<<<<<<<<<<<< 
 * 
 * def pylocslist(*args):
 */
  __pyx_2 = PyString_AsString(__pyx_v_inname); if (unlikely((!__pyx_2) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
  __pyx_4 = PyString_AsString(__pyx_v_outname); if (unlikely((!__pyx_4) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(add_locs(__pyx_2,__pyx_4)); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("blast_misc.pyaddlocs");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF(__pyx_v_inname);
  Py_DECREF(__pyx_v_outname);
  return __pyx_r;
}

/* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":65
 *     return add_locs(inname, outname)
 * 
 * def pylocslist(*args):             # <<<<<<<<<<<<<< 
 *     """ take a list of files to update inplace """
 *     if isinstance(args[0], list):
 */

static PyObject *__pyx_pf_10blast_misc_pylocslist(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_10blast_misc_pylocslist[] = " take a list of files to update inplace ";
static PyObject *__pyx_pf_10blast_misc_pylocslist(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_args = 0;
  PyObject *__pyx_v_a;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  int __pyx_3;
  Py_ssize_t __pyx_4;
  char *__pyx_5;
  static char *__pyx_argnames[] = {0};
  if (__Pyx_GetStarArgs(&__pyx_args, &__pyx_kwds, __pyx_argnames, 0, &__pyx_v_args, 0, 0) < 0) return NULL;
  if (unlikely(!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames))) {
    Py_XDECREF(__pyx_args);
    Py_XDECREF(__pyx_kwds);
    Py_XDECREF(__pyx_v_args);
    return NULL;
  }
  __pyx_v_a = Py_None; Py_INCREF(Py_None);

  /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":67
 * def pylocslist(*args):
 *     """ take a list of files to update inplace """
 *     if isinstance(args[0], list):             # <<<<<<<<<<<<<< 
 *         args = args[0]
 *     for a in args:
 */
  if (PyList_CheckExact(__pyx_v_args) && 0 <= 0 && 0 < PyList_GET_SIZE(__pyx_v_args)) {
    __pyx_2 = PyList_GET_ITEM(__pyx_v_args, 0); Py_INCREF(__pyx_2);
    } else if (PyTuple_CheckExact(__pyx_v_args) && 0 <= 0 && 0 < PyTuple_GET_SIZE(__pyx_v_args)) {
    __pyx_2 = PyTuple_GET_ITEM(__pyx_v_args, 0); Py_INCREF(__pyx_2);
    } else {
    __pyx_1 = PyInt_FromLong(0); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; goto __pyx_L1;}
    __pyx_2 = PyObject_GetItem(__pyx_v_args, __pyx_1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
  }
  __pyx_3 = PyObject_IsInstance(__pyx_2,((PyObject*)&PyList_Type)); if (unlikely(__pyx_3 == -1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (__pyx_3) {

    /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":68
 *     """ take a list of files to update inplace """
 *     if isinstance(args[0], list):
 *         args = args[0]             # <<<<<<<<<<<<<< 
 *     for a in args:
 *         print add_locs(a, NULL)
 */
    if (PyList_CheckExact(__pyx_v_args) && 0 <= 0 && 0 < PyList_GET_SIZE(__pyx_v_args)) {
      __pyx_2 = PyList_GET_ITEM(__pyx_v_args, 0); Py_INCREF(__pyx_2);
      } else if (PyTuple_CheckExact(__pyx_v_args) && 0 <= 0 && 0 < PyTuple_GET_SIZE(__pyx_v_args)) {
      __pyx_2 = PyTuple_GET_ITEM(__pyx_v_args, 0); Py_INCREF(__pyx_2);
      } else {
      __pyx_1 = PyInt_FromLong(0); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; goto __pyx_L1;}
      __pyx_2 = PyObject_GetItem(__pyx_v_args, __pyx_1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; goto __pyx_L1;}
      Py_DECREF(__pyx_1); __pyx_1 = 0;
    }
    Py_DECREF(__pyx_v_args);
    __pyx_v_args = __pyx_2;
    __pyx_2 = 0;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":69
 *     if isinstance(args[0], list):
 *         args = args[0]
 *     for a in args:             # <<<<<<<<<<<<<< 
 *         print add_locs(a, NULL)
 * 
 */
  if (PyList_CheckExact(__pyx_v_args)) { __pyx_4 = 0; __pyx_1 = __pyx_v_args; Py_INCREF(__pyx_1); }
  else { __pyx_1 = PyObject_GetIter(__pyx_v_args); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 69; goto __pyx_L1;} }
  for (;;) {
    if (PyList_CheckExact(__pyx_1)) { if (__pyx_4 >= PyList_GET_SIZE(__pyx_1)) break; __pyx_2 = PyList_GET_ITEM(__pyx_1, __pyx_4++); Py_INCREF(__pyx_2); }
    else {
      __pyx_2 = PyIter_Next(__pyx_1);
      if (!__pyx_2) {
        break;
      }
    }
    Py_DECREF(__pyx_v_a);
    __pyx_v_a = __pyx_2;
    __pyx_2 = 0;

    /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":70
 *         args = args[0]
 *     for a in args:
 *         print add_locs(a, NULL)             # <<<<<<<<<<<<<< 
 * 
 * 
 */
    __pyx_5 = PyString_AsString(__pyx_v_a); if (unlikely((!__pyx_5) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; goto __pyx_L1;}
    __pyx_2 = PyInt_FromLong(add_locs(__pyx_5,NULL)); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; goto __pyx_L1;}
    if (__Pyx_PrintItem(__pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    if (__Pyx_PrintNewline() < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; goto __pyx_L1;}
  }
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("blast_misc.pylocslist");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_XDECREF(__pyx_v_args);
  Py_DECREF(__pyx_v_a);
  Py_XDECREF(__pyx_args);
  Py_XDECREF(__pyx_kwds);
  return __pyx_r;
}

/* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":73
 * 
 * 
 * def _blast_array(blastf, maxkeep):             # <<<<<<<<<<<<<< 
 *     cdef int qlen = 8, slen = 8, hlen, nmiss, ngap, qstart, qstop, sstart, sstop, icol = 0
 *     cdef float pct = 0.0, evalue = 0.0, bit = 0.0
 */

static PyObject *__pyx_num_10;

static PyObject *__pyx_n_defaultdict;
static PyObject *__pyx_n__;
static PyObject *__pyx_n_sorted;
static PyObject *__pyx_n_itemgetter;
static PyObject *__pyx_n_key;

static PyObject *__pyx_builtin_sorted;

static char __pyx_k38[] = "r";

static PyObject *__pyx_pf_10blast_misc__blast_array(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_pf_10blast_misc__blast_array(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_blastf = 0;
  PyObject *__pyx_v_maxkeep = 0;
  int __pyx_v_qlen;
  int __pyx_v_slen;
  int __pyx_v_hlen;
  int __pyx_v_nmiss;
  int __pyx_v_ngap;
  int __pyx_v_qstart;
  int __pyx_v_qstop;
  int __pyx_v_sstart;
  int __pyx_v_sstop;
  int __pyx_v_icol;
  float __pyx_v_pct;
  float __pyx_v_evalue;
  float __pyx_v_bit;
  char __pyx_v_qname[128];
  char __pyx_v_sname[128];
  FILE *__pyx_v_fh;
  PyObject *__pyx_v_recs;
  PyObject *__pyx_v_arr;
  PyObject *__pyx_v_k;
  PyObject *__pyx_v_v;
  PyObject *__pyx_v_li;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  char *__pyx_5;
  PyObject *__pyx_6 = 0;
  PyObject *__pyx_7 = 0;
  PyObject *__pyx_8 = 0;
  PyObject *__pyx_9 = 0;
  PyObject *__pyx_10 = 0;
  PyObject *__pyx_11 = 0;
  PyObject *__pyx_12 = 0;
  PyObject *__pyx_13 = 0;
  PyObject *__pyx_14 = 0;
  PyObject *__pyx_15 = 0;
  PyObject *__pyx_16 = 0;
  int __pyx_17;
  Py_ssize_t __pyx_18;
  Py_ssize_t __pyx_19;
  Py_ssize_t __pyx_20;
  static char *__pyx_argnames[] = {"blastf","maxkeep",0};
  if (unlikely(!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_blastf, &__pyx_v_maxkeep))) return NULL;
  Py_INCREF(__pyx_v_blastf);
  Py_INCREF(__pyx_v_maxkeep);
  __pyx_v_recs = Py_None; Py_INCREF(Py_None);
  __pyx_v_arr = Py_None; Py_INCREF(Py_None);
  __pyx_v_k = Py_None; Py_INCREF(Py_None);
  __pyx_v_v = Py_None; Py_INCREF(Py_None);
  __pyx_v_li = Py_None; Py_INCREF(Py_None);

  /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":74
 * 
 * def _blast_array(blastf, maxkeep):
 *     cdef int qlen = 8, slen = 8, hlen, nmiss, ngap, qstart, qstop, sstart, sstop, icol = 0             # <<<<<<<<<<<<<< 
 *     cdef float pct = 0.0, evalue = 0.0, bit = 0.0
 *     cdef char qname[128], sname[128]
 */
  __pyx_v_qlen = 8;

  __pyx_v_slen = 8;

  __pyx_v_icol = 0;


  /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":75
 * def _blast_array(blastf, maxkeep):
 *     cdef int qlen = 8, slen = 8, hlen, nmiss, ngap, qstart, qstop, sstart, sstop, icol = 0
 *     cdef float pct = 0.0, evalue = 0.0, bit = 0.0             # <<<<<<<<<<<<<< 
 *     cdef char qname[128], sname[128]
 *     cdef char *tmp
 */
  __pyx_v_pct = 0.0;

  __pyx_v_evalue = 0.0;

  __pyx_v_bit = 0.0;


  /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":80
 *     cdef FILE *fh
 * 
 *     if maxkeep == None: maxkeep = 6             # <<<<<<<<<<<<<< 
 * 
 *     recs = collections.defaultdict(list)
 */
  __pyx_1 = PyObject_RichCompare(__pyx_v_maxkeep, Py_None, Py_EQ); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; goto __pyx_L1;}
  __pyx_2 = __Pyx_PyObject_IsTrue(__pyx_1); if (unlikely(__pyx_2 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (__pyx_2) {
    Py_INCREF(__pyx_num_6);
    Py_DECREF(__pyx_v_maxkeep);
    __pyx_v_maxkeep = __pyx_num_6;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":82
 *     if maxkeep == None: maxkeep = 6
 * 
 *     recs = collections.defaultdict(list)             # <<<<<<<<<<<<<< 
 *     fh = fopen(blastf, "r")
 * 
 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_collections); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; goto __pyx_L1;}
  __pyx_3 = PyObject_GetAttr(__pyx_1, __pyx_n_defaultdict); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyTuple_New(1); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; goto __pyx_L1;}
  Py_INCREF(((PyObject*)&PyList_Type));
  PyTuple_SET_ITEM(__pyx_1, 0, ((PyObject*)&PyList_Type));
  __pyx_4 = PyObject_CallObject(__pyx_3, __pyx_1); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_v_recs);
  __pyx_v_recs = __pyx_4;
  __pyx_4 = 0;

  /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":83
 * 
 *     recs = collections.defaultdict(list)
 *     fh = fopen(blastf, "r")             # <<<<<<<<<<<<<< 
 * 
 *     while fscanf(fh, blast_format, qname, sname, &pct, &hlen, &nmiss, &ngap, &qstart, &qstop, &sstart, &sstop, &evalue, &bit ) != EOF:
 */
  __pyx_5 = PyString_AsString(__pyx_v_blastf); if (unlikely((!__pyx_5) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 83; goto __pyx_L1;}
  __pyx_v_fh = fopen(__pyx_5,__pyx_k38);

  /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":85
 *     fh = fopen(blastf, "r")
 * 
 *     while fscanf(fh, blast_format, qname, sname, &pct, &hlen, &nmiss, &ngap, &qstart, &qstop, &sstart, &sstop, &evalue, &bit ) != EOF:             # <<<<<<<<<<<<<< 
 *         if strlen(qname) > qlen: qlen = strlen(qname)
 *         if strlen(sname) > slen: slen = strlen(sname)
 */
  while (1) {
    __pyx_2 = (fscanf(__pyx_v_fh,__pyx_v_10blast_misc_blast_format,__pyx_v_qname,__pyx_v_sname,(&__pyx_v_pct),(&__pyx_v_hlen),(&__pyx_v_nmiss),(&__pyx_v_ngap),(&__pyx_v_qstart),(&__pyx_v_qstop),(&__pyx_v_sstart),(&__pyx_v_sstop),(&__pyx_v_evalue),(&__pyx_v_bit)) != EOF);
    if (!__pyx_2) break;

    /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":86
 * 
 *     while fscanf(fh, blast_format, qname, sname, &pct, &hlen, &nmiss, &ngap, &qstart, &qstop, &sstart, &sstop, &evalue, &bit ) != EOF:
 *         if strlen(qname) > qlen: qlen = strlen(qname)             # <<<<<<<<<<<<<< 
 *         if strlen(sname) > slen: slen = strlen(sname)
 * 
 */
    __pyx_2 = (strlen(__pyx_v_qname) > __pyx_v_qlen);
    if (__pyx_2) {
      __pyx_v_qlen = strlen(__pyx_v_qname);
      goto __pyx_L5;
    }
    __pyx_L5:;

    /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":87
 *     while fscanf(fh, blast_format, qname, sname, &pct, &hlen, &nmiss, &ngap, &qstart, &qstop, &sstart, &sstop, &evalue, &bit ) != EOF:
 *         if strlen(qname) > qlen: qlen = strlen(qname)
 *         if strlen(sname) > slen: slen = strlen(sname)             # <<<<<<<<<<<<<< 
 * 
 *         #key = qname + '_' + sname
 */
    __pyx_2 = (strlen(__pyx_v_sname) > __pyx_v_slen);
    if (__pyx_2) {
      __pyx_v_slen = strlen(__pyx_v_sname);
      goto __pyx_L6;
    }
    __pyx_L6:;

    /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":90
 * 
 *         #key = qname + '_' + sname
 *         PyList_Append(recs[qname + '_' + sname], [qname, sname, pct, hlen, nmiss, ngap, qstart, qstop, sstart, sstop, evalue, bit, None, False])             # <<<<<<<<<<<<<< 
 *     fclose(fh)
 * 
 */
    __pyx_3 = PyString_FromString(__pyx_v_qname); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; goto __pyx_L1;}
    __pyx_1 = PyNumber_Add(__pyx_3, __pyx_n__); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_4 = PyString_FromString(__pyx_v_sname); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; goto __pyx_L1;}
    __pyx_3 = PyNumber_Add(__pyx_1, __pyx_4); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __pyx_1 = PyObject_GetItem(__pyx_v_recs, __pyx_3); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_4 = PyString_FromString(__pyx_v_qname); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; goto __pyx_L1;}
    __pyx_3 = PyString_FromString(__pyx_v_sname); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; goto __pyx_L1;}
    __pyx_6 = PyFloat_FromDouble(__pyx_v_pct); if (unlikely(!__pyx_6)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; goto __pyx_L1;}
    __pyx_7 = PyInt_FromLong(__pyx_v_hlen); if (unlikely(!__pyx_7)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; goto __pyx_L1;}
    __pyx_8 = PyInt_FromLong(__pyx_v_nmiss); if (unlikely(!__pyx_8)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; goto __pyx_L1;}
    __pyx_9 = PyInt_FromLong(__pyx_v_ngap); if (unlikely(!__pyx_9)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; goto __pyx_L1;}
    __pyx_10 = PyInt_FromLong(__pyx_v_qstart); if (unlikely(!__pyx_10)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; goto __pyx_L1;}
    __pyx_11 = PyInt_FromLong(__pyx_v_qstop); if (unlikely(!__pyx_11)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; goto __pyx_L1;}
    __pyx_12 = PyInt_FromLong(__pyx_v_sstart); if (unlikely(!__pyx_12)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; goto __pyx_L1;}
    __pyx_13 = PyInt_FromLong(__pyx_v_sstop); if (unlikely(!__pyx_13)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; goto __pyx_L1;}
    __pyx_14 = PyFloat_FromDouble(__pyx_v_evalue); if (unlikely(!__pyx_14)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; goto __pyx_L1;}
    __pyx_15 = PyFloat_FromDouble(__pyx_v_bit); if (unlikely(!__pyx_15)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; goto __pyx_L1;}
    __pyx_16 = PyList_New(14); if (unlikely(!__pyx_16)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; goto __pyx_L1;}
    PyList_SET_ITEM(__pyx_16, 0, __pyx_4);
    PyList_SET_ITEM(__pyx_16, 1, __pyx_3);
    PyList_SET_ITEM(__pyx_16, 2, __pyx_6);
    PyList_SET_ITEM(__pyx_16, 3, __pyx_7);
    PyList_SET_ITEM(__pyx_16, 4, __pyx_8);
    PyList_SET_ITEM(__pyx_16, 5, __pyx_9);
    PyList_SET_ITEM(__pyx_16, 6, __pyx_10);
    PyList_SET_ITEM(__pyx_16, 7, __pyx_11);
    PyList_SET_ITEM(__pyx_16, 8, __pyx_12);
    PyList_SET_ITEM(__pyx_16, 9, __pyx_13);
    PyList_SET_ITEM(__pyx_16, 10, __pyx_14);
    PyList_SET_ITEM(__pyx_16, 11, __pyx_15);
    Py_INCREF(Py_None);
    PyList_SET_ITEM(__pyx_16, 12, Py_None);
    Py_INCREF(Py_False);
    PyList_SET_ITEM(__pyx_16, 13, Py_False);
    __pyx_4 = 0;
    __pyx_3 = 0;
    __pyx_6 = 0;
    __pyx_7 = 0;
    __pyx_8 = 0;
    __pyx_9 = 0;
    __pyx_10 = 0;
    __pyx_11 = 0;
    __pyx_12 = 0;
    __pyx_13 = 0;
    __pyx_14 = 0;
    __pyx_15 = 0;
    __pyx_17 = PyList_Append(__pyx_1,__pyx_16); if (unlikely(__pyx_17 == -1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_16); __pyx_16 = 0;
  }

  /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":91
 *         #key = qname + '_' + sname
 *         PyList_Append(recs[qname + '_' + sname], [qname, sname, pct, hlen, nmiss, ngap, qstart, qstop, sstart, sstop, evalue, bit, None, False])
 *     fclose(fh)             # <<<<<<<<<<<<<< 
 * 
 *     arr = [] #PyList_New(0)
 */
  fclose(__pyx_v_fh);

  /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":93
 *     fclose(fh)
 * 
 *     arr = [] #PyList_New(0)             # <<<<<<<<<<<<<< 
 *     # this is faster then using k,v in rec.items()
 *     for k in sorted(recs, key=operator.itemgetter(1)):
 */
  __pyx_4 = PyList_New(0); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
  Py_DECREF(__pyx_v_arr);
  __pyx_v_arr = __pyx_4;
  __pyx_4 = 0;

  /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":95
 *     arr = [] #PyList_New(0)
 *     # this is faster then using k,v in rec.items()
 *     for k in sorted(recs, key=operator.itemgetter(1)):             # <<<<<<<<<<<<<< 
 *         v = PyDict_GetItem(recs, k)  # was: v = recs[k]
 *         icol = 0
 */
  __pyx_3 = PyTuple_New(1); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
  Py_INCREF(__pyx_v_recs);
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_recs);
  __pyx_6 = PyDict_New(); if (unlikely(!__pyx_6)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
  __pyx_7 = __Pyx_GetName(__pyx_m, __pyx_n_operator); if (unlikely(!__pyx_7)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
  __pyx_8 = PyObject_GetAttr(__pyx_7, __pyx_n_itemgetter); if (unlikely(!__pyx_8)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
  Py_DECREF(__pyx_7); __pyx_7 = 0;
  __pyx_9 = PyTuple_New(1); if (unlikely(!__pyx_9)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
  Py_INCREF(__pyx_num_1);
  PyTuple_SET_ITEM(__pyx_9, 0, __pyx_num_1);
  __pyx_10 = PyObject_CallObject(__pyx_8, __pyx_9); if (unlikely(!__pyx_10)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
  Py_DECREF(__pyx_8); __pyx_8 = 0;
  Py_DECREF(__pyx_9); __pyx_9 = 0;
  if (PyDict_SetItem(__pyx_6, __pyx_n_key, __pyx_10) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
  Py_DECREF(__pyx_10); __pyx_10 = 0;
  __pyx_11 = PyEval_CallObjectWithKeywords(__pyx_builtin_sorted, __pyx_3, __pyx_6); if (unlikely(!__pyx_11)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_6); __pyx_6 = 0;
  if (PyList_CheckExact(__pyx_11)) { __pyx_18 = 0; __pyx_12 = __pyx_11; Py_INCREF(__pyx_12); }
  else { __pyx_12 = PyObject_GetIter(__pyx_11); if (unlikely(!__pyx_12)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;} }
  Py_DECREF(__pyx_11); __pyx_11 = 0;
  for (;;) {
    if (PyList_CheckExact(__pyx_12)) { if (__pyx_18 >= PyList_GET_SIZE(__pyx_12)) break; __pyx_13 = PyList_GET_ITEM(__pyx_12, __pyx_18++); Py_INCREF(__pyx_13); }
    else {
      __pyx_13 = PyIter_Next(__pyx_12);
      if (!__pyx_13) {
        break;
      }
    }
    Py_DECREF(__pyx_v_k);
    __pyx_v_k = __pyx_13;
    __pyx_13 = 0;

    /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":96
 *     # this is faster then using k,v in rec.items()
 *     for k in sorted(recs, key=operator.itemgetter(1)):
 *         v = PyDict_GetItem(recs, k)  # was: v = recs[k]             # <<<<<<<<<<<<<< 
 *         icol = 0
 *         for li in sorted(v, key=operator.itemgetter(10))[:maxkeep]:
 */
    __pyx_14 = PyDict_GetItem(__pyx_v_recs,__pyx_v_k); if (unlikely(!__pyx_14)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 96; goto __pyx_L1;}
    Py_DECREF(__pyx_v_v);
    __pyx_v_v = __pyx_14;
    __pyx_14 = 0;

    /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":97
 *     for k in sorted(recs, key=operator.itemgetter(1)):
 *         v = PyDict_GetItem(recs, k)  # was: v = recs[k]
 *         icol = 0             # <<<<<<<<<<<<<< 
 *         for li in sorted(v, key=operator.itemgetter(10))[:maxkeep]:
 *             # set the first to have hit_rank=0
 */
    __pyx_v_icol = 0;

    /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":98
 *         v = PyDict_GetItem(recs, k)  # was: v = recs[k]
 *         icol = 0
 *         for li in sorted(v, key=operator.itemgetter(10))[:maxkeep]:             # <<<<<<<<<<<<<< 
 *             # set the first to have hit_rank=0
 *             li[12] = icol
 */
    __pyx_15 = PyTuple_New(1); if (unlikely(!__pyx_15)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; goto __pyx_L1;}
    Py_INCREF(__pyx_v_v);
    PyTuple_SET_ITEM(__pyx_15, 0, __pyx_v_v);
    __pyx_1 = PyDict_New(); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; goto __pyx_L1;}
    __pyx_16 = __Pyx_GetName(__pyx_m, __pyx_n_operator); if (unlikely(!__pyx_16)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; goto __pyx_L1;}
    __pyx_4 = PyObject_GetAttr(__pyx_16, __pyx_n_itemgetter); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; goto __pyx_L1;}
    Py_DECREF(__pyx_16); __pyx_16 = 0;
    __pyx_7 = PyTuple_New(1); if (unlikely(!__pyx_7)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; goto __pyx_L1;}
    Py_INCREF(__pyx_num_10);
    PyTuple_SET_ITEM(__pyx_7, 0, __pyx_num_10);
    __pyx_8 = PyObject_CallObject(__pyx_4, __pyx_7); if (unlikely(!__pyx_8)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_7); __pyx_7 = 0;
    if (PyDict_SetItem(__pyx_1, __pyx_n_key, __pyx_8) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; goto __pyx_L1;}
    Py_DECREF(__pyx_8); __pyx_8 = 0;
    __pyx_9 = PyEval_CallObjectWithKeywords(__pyx_builtin_sorted, __pyx_15, __pyx_1); if (unlikely(!__pyx_9)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; goto __pyx_L1;}
    Py_DECREF(__pyx_15); __pyx_15 = 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_20 = __pyx_PyIndex_AsSsize_t(__pyx_v_maxkeep); if (unlikely((__pyx_20 == -1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; goto __pyx_L1;}
    __pyx_10 = PySequence_GetSlice(__pyx_9, 0, __pyx_20); if (unlikely(!__pyx_10)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; goto __pyx_L1;}
    Py_DECREF(__pyx_9); __pyx_9 = 0;
    if (PyList_CheckExact(__pyx_10)) { __pyx_19 = 0; __pyx_3 = __pyx_10; Py_INCREF(__pyx_3); }
    else { __pyx_3 = PyObject_GetIter(__pyx_10); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; goto __pyx_L1;} }
    Py_DECREF(__pyx_10); __pyx_10 = 0;
    for (;;) {
      if (PyList_CheckExact(__pyx_3)) { if (__pyx_19 >= PyList_GET_SIZE(__pyx_3)) break; __pyx_6 = PyList_GET_ITEM(__pyx_3, __pyx_19++); Py_INCREF(__pyx_6); }
      else {
        __pyx_6 = PyIter_Next(__pyx_3);
        if (!__pyx_6) {
          break;
        }
      }
      Py_DECREF(__pyx_v_li);
      __pyx_v_li = __pyx_6;
      __pyx_6 = 0;

      /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":100
 *         for li in sorted(v, key=operator.itemgetter(10))[:maxkeep]:
 *             # set the first to have hit_rank=0
 *             li[12] = icol             # <<<<<<<<<<<<<< 
 *             icol += 1
 *             PyList_Append(arr, li)
 */
      __pyx_11 = PyInt_FromLong(__pyx_v_icol); if (unlikely(!__pyx_11)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}
      if (PyList_CheckExact(__pyx_v_li) && 0 <= 12 && 12 < PyList_GET_SIZE(__pyx_v_li)) {
        Py_DECREF(PyList_GET_ITEM(__pyx_v_li, 12)); Py_INCREF(__pyx_11);
        PyList_SET_ITEM(__pyx_v_li, 12, __pyx_11);
        } else {
        __pyx_13 = PyInt_FromLong(12); if (unlikely(!__pyx_13)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}
        if (PyObject_SetItem(__pyx_v_li, __pyx_13, __pyx_11) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}
        Py_DECREF(__pyx_13); __pyx_13 = 0;
      }
      Py_DECREF(__pyx_11); __pyx_11 = 0;

      /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":101
 *             # set the first to have hit_rank=0
 *             li[12] = icol
 *             icol += 1             # <<<<<<<<<<<<<< 
 *             PyList_Append(arr, li)
 *     return arr, qlen, slen
 */
      __pyx_v_icol += 1;

      /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":102
 *             li[12] = icol
 *             icol += 1
 *             PyList_Append(arr, li)             # <<<<<<<<<<<<<< 
 *     return arr, qlen, slen
 * 
 */
      __pyx_17 = PyList_Append(__pyx_v_arr,__pyx_v_li); if (unlikely(__pyx_17 == -1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; goto __pyx_L1;}
    }
    Py_DECREF(__pyx_3); __pyx_3 = 0;
  }
  Py_DECREF(__pyx_12); __pyx_12 = 0;

  /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":103
 *             icol += 1
 *             PyList_Append(arr, li)
 *     return arr, qlen, slen             # <<<<<<<<<<<<<< 
 * 
 * 
 */
  __pyx_14 = PyInt_FromLong(__pyx_v_qlen); if (unlikely(!__pyx_14)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 103; goto __pyx_L1;}
  __pyx_16 = PyInt_FromLong(__pyx_v_slen); if (unlikely(!__pyx_16)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 103; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(3); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 103; goto __pyx_L1;}
  Py_INCREF(__pyx_v_arr);
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_v_arr);
  PyTuple_SET_ITEM(__pyx_4, 1, __pyx_14);
  PyTuple_SET_ITEM(__pyx_4, 2, __pyx_16);
  __pyx_14 = 0;
  __pyx_16 = 0;
  __pyx_r = __pyx_4;
  __pyx_4 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_6);
  Py_XDECREF(__pyx_7);
  Py_XDECREF(__pyx_8);
  Py_XDECREF(__pyx_9);
  Py_XDECREF(__pyx_10);
  Py_XDECREF(__pyx_11);
  Py_XDECREF(__pyx_12);
  Py_XDECREF(__pyx_13);
  Py_XDECREF(__pyx_14);
  Py_XDECREF(__pyx_15);
  Py_XDECREF(__pyx_16);
  __Pyx_AddTraceback("blast_misc._blast_array");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF(__pyx_v_recs);
  Py_DECREF(__pyx_v_arr);
  Py_DECREF(__pyx_v_k);
  Py_DECREF(__pyx_v_v);
  Py_DECREF(__pyx_v_li);
  Py_DECREF(__pyx_v_blastf);
  Py_DECREF(__pyx_v_maxkeep);
  return __pyx_r;
}

/* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":106
 * 
 * 
 * def blast_array(fi, dopickle=1, best_hit=1, maxkeep=6):             # <<<<<<<<<<<<<< 
 *     file_name = 0
 *     if not isinstance(fi, list) and type(fi) != numpy.recarray:
 */

static PyObject *__pyx_num_0;

static PyObject *__pyx_n_recarray;
static PyObject *__pyx_n_path;
static PyObject *__pyx_n_exists;
static PyObject *__pyx_n_load;
static PyObject *__pyx_n__blast_array;
static PyObject *__pyx_n_S;
static PyObject *__pyx_n_rec;
static PyObject *__pyx_n_array;
static PyObject *__pyx_n_names;
static PyObject *__pyx_n_formats;
static PyObject *__pyx_n_dump;

static PyObject *__pyx_k42p;

static char __pyx_k42[] = ".pickle";

static PyObject *__pyx_pf_10blast_misc_blast_array(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_pf_10blast_misc_blast_array(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_fi = 0;
  PyObject *__pyx_v_dopickle = 0;
  PyObject *__pyx_v_best_hit = 0;
  PyObject *__pyx_v_maxkeep = 0;
  PyObject *__pyx_v_file_name;
  PyObject *__pyx_v_arr;
  PyObject *__pyx_v_qlen;
  PyObject *__pyx_v_slen;
  PyObject *__pyx_v_ra;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  int __pyx_6;
  Py_ssize_t __pyx_7;
  static char *__pyx_argnames[] = {"fi","dopickle","best_hit","maxkeep",0};
  __pyx_v_dopickle = __pyx_k35;
  __pyx_v_best_hit = __pyx_k36;
  __pyx_v_maxkeep = __pyx_k37;
  if (unlikely(!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O|OOO", __pyx_argnames, &__pyx_v_fi, &__pyx_v_dopickle, &__pyx_v_best_hit, &__pyx_v_maxkeep))) return NULL;
  Py_INCREF(__pyx_v_fi);
  Py_INCREF(__pyx_v_dopickle);
  Py_INCREF(__pyx_v_best_hit);
  Py_INCREF(__pyx_v_maxkeep);
  __pyx_v_file_name = Py_None; Py_INCREF(Py_None);
  __pyx_v_arr = Py_None; Py_INCREF(Py_None);
  __pyx_v_qlen = Py_None; Py_INCREF(Py_None);
  __pyx_v_slen = Py_None; Py_INCREF(Py_None);
  __pyx_v_ra = Py_None; Py_INCREF(Py_None);

  /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":107
 * 
 * def blast_array(fi, dopickle=1, best_hit=1, maxkeep=6):
 *     file_name = 0             # <<<<<<<<<<<<<< 
 *     if not isinstance(fi, list) and type(fi) != numpy.recarray:
 *         file_name = fi + ".pickle"
 */
  Py_INCREF(__pyx_num_0);
  Py_DECREF(__pyx_v_file_name);
  __pyx_v_file_name = __pyx_num_0;

  /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":108
 * def blast_array(fi, dopickle=1, best_hit=1, maxkeep=6):
 *     file_name = 0
 *     if not isinstance(fi, list) and type(fi) != numpy.recarray:             # <<<<<<<<<<<<<< 
 *         file_name = fi + ".pickle"
 * 
 */
  __pyx_2 = PyObject_IsInstance(__pyx_v_fi,((PyObject*)&PyList_Type)); if (unlikely(__pyx_2 == -1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; goto __pyx_L1;}
  __pyx_1 = __Pyx_PyBool_FromLong((!__pyx_2)); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; goto __pyx_L1;}
  __pyx_2 = __Pyx_PyObject_IsTrue(__pyx_1); if (unlikely(__pyx_2 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; goto __pyx_L1;}
  if (__pyx_2) {
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_3 = PyTuple_New(1); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; goto __pyx_L1;}
    Py_INCREF(__pyx_v_fi);
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_fi);
    __pyx_4 = PyObject_CallObject(((PyObject*)&PyType_Type), __pyx_3); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n_numpy); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; goto __pyx_L1;}
    __pyx_5 = PyObject_GetAttr(__pyx_3, __pyx_n_recarray); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_1 = PyObject_RichCompare(__pyx_4, __pyx_5, Py_NE); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_5); __pyx_5 = 0;
  }
  __pyx_2 = __Pyx_PyObject_IsTrue(__pyx_1); if (unlikely(__pyx_2 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (__pyx_2) {

    /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":109
 *     file_name = 0
 *     if not isinstance(fi, list) and type(fi) != numpy.recarray:
 *         file_name = fi + ".pickle"             # <<<<<<<<<<<<<< 
 * 
 *         if dopickle and os.path.exists(file_name):
 */
    __pyx_3 = PyNumber_Add(__pyx_v_fi, __pyx_k42p); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 109; goto __pyx_L1;}
    Py_DECREF(__pyx_v_file_name);
    __pyx_v_file_name = __pyx_3;
    __pyx_3 = 0;

    /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":111
 *         file_name = fi + ".pickle"
 * 
 *         if dopickle and os.path.exists(file_name):             # <<<<<<<<<<<<<< 
 *             if not best_hit:
 *                 return numpy.load(file_name)
 */
    __pyx_4 = __pyx_v_dopickle;
    Py_INCREF(__pyx_4);
    __pyx_2 = __Pyx_PyObject_IsTrue(__pyx_4); if (unlikely(__pyx_2 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 111; goto __pyx_L1;}
    if (__pyx_2) {
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      __pyx_5 = __Pyx_GetName(__pyx_m, __pyx_n_os); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 111; goto __pyx_L1;}
      __pyx_1 = PyObject_GetAttr(__pyx_5, __pyx_n_path); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 111; goto __pyx_L1;}
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      __pyx_3 = PyObject_GetAttr(__pyx_1, __pyx_n_exists); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 111; goto __pyx_L1;}
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      __pyx_5 = PyTuple_New(1); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 111; goto __pyx_L1;}
      Py_INCREF(__pyx_v_file_name);
      PyTuple_SET_ITEM(__pyx_5, 0, __pyx_v_file_name);
      __pyx_4 = PyObject_CallObject(__pyx_3, __pyx_5); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 111; goto __pyx_L1;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      Py_DECREF(__pyx_5); __pyx_5 = 0;
    }
    __pyx_2 = __Pyx_PyObject_IsTrue(__pyx_4); if (unlikely(__pyx_2 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 111; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    if (__pyx_2) {

      /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":112
 * 
 *         if dopickle and os.path.exists(file_name):
 *             if not best_hit:             # <<<<<<<<<<<<<< 
 *                 return numpy.load(file_name)
 *             else:
 */
      __pyx_2 = __Pyx_PyObject_IsTrue(__pyx_v_best_hit); if (unlikely(__pyx_2 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 112; goto __pyx_L1;}
      __pyx_6 = (!__pyx_2);
      if (__pyx_6) {

        /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":113
 *         if dopickle and os.path.exists(file_name):
 *             if not best_hit:
 *                 return numpy.load(file_name)             # <<<<<<<<<<<<<< 
 *             else:
 *                 arr = numpy.load(file_name)
 */
        __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_numpy); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 113; goto __pyx_L1;}
        __pyx_3 = PyObject_GetAttr(__pyx_1, __pyx_n_load); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 113; goto __pyx_L1;}
        Py_DECREF(__pyx_1); __pyx_1 = 0;
        __pyx_5 = PyTuple_New(1); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 113; goto __pyx_L1;}
        Py_INCREF(__pyx_v_file_name);
        PyTuple_SET_ITEM(__pyx_5, 0, __pyx_v_file_name);
        __pyx_4 = PyObject_CallObject(__pyx_3, __pyx_5); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 113; goto __pyx_L1;}
        Py_DECREF(__pyx_3); __pyx_3 = 0;
        Py_DECREF(__pyx_5); __pyx_5 = 0;
        __pyx_r = __pyx_4;
        __pyx_4 = 0;
        goto __pyx_L0;
        goto __pyx_L4;
      }
      /*else*/ {

        /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":115
 *                 return numpy.load(file_name)
 *             else:
 *                 arr = numpy.load(file_name)             # <<<<<<<<<<<<<< 
 *                 return arr[arr['hit_rank'] == 0]
 * 
 */
        __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_numpy); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; goto __pyx_L1;}
        __pyx_3 = PyObject_GetAttr(__pyx_1, __pyx_n_load); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; goto __pyx_L1;}
        Py_DECREF(__pyx_1); __pyx_1 = 0;
        __pyx_5 = PyTuple_New(1); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; goto __pyx_L1;}
        Py_INCREF(__pyx_v_file_name);
        PyTuple_SET_ITEM(__pyx_5, 0, __pyx_v_file_name);
        __pyx_4 = PyObject_CallObject(__pyx_3, __pyx_5); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; goto __pyx_L1;}
        Py_DECREF(__pyx_3); __pyx_3 = 0;
        Py_DECREF(__pyx_5); __pyx_5 = 0;
        Py_DECREF(__pyx_v_arr);
        __pyx_v_arr = __pyx_4;
        __pyx_4 = 0;

        /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":116
 *             else:
 *                 arr = numpy.load(file_name)
 *                 return arr[arr['hit_rank'] == 0]             # <<<<<<<<<<<<<< 
 * 
 *         arr, qlen, slen = _blast_array(fi, maxkeep)
 */
        __pyx_1 = PyObject_GetItem(__pyx_v_arr, __pyx_n_hit_rank); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 116; goto __pyx_L1;}
        __pyx_3 = PyObject_RichCompare(__pyx_1, __pyx_num_0, Py_EQ); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 116; goto __pyx_L1;}
        Py_DECREF(__pyx_1); __pyx_1 = 0;
        __pyx_5 = PyObject_GetItem(__pyx_v_arr, __pyx_3); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 116; goto __pyx_L1;}
        Py_DECREF(__pyx_3); __pyx_3 = 0;
        __pyx_r = __pyx_5;
        __pyx_5 = 0;
        goto __pyx_L0;
      }
      __pyx_L4:;
      goto __pyx_L3;
    }
    __pyx_L3:;

    /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":118
 *                 return arr[arr['hit_rank'] == 0]
 * 
 *         arr, qlen, slen = _blast_array(fi, maxkeep)             # <<<<<<<<<<<<<< 
 *         BLAST_TYPES[0] = 'S' + str(qlen)
 *         BLAST_TYPES[1] = 'S' + str(slen)
 */
    __pyx_4 = __Pyx_GetName(__pyx_m, __pyx_n__blast_array); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
    __pyx_1 = PyTuple_New(2); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
    Py_INCREF(__pyx_v_fi);
    PyTuple_SET_ITEM(__pyx_1, 0, __pyx_v_fi);
    Py_INCREF(__pyx_v_maxkeep);
    PyTuple_SET_ITEM(__pyx_1, 1, __pyx_v_maxkeep);
    __pyx_3 = PyObject_CallObject(__pyx_4, __pyx_1); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    if (PyTuple_CheckExact(__pyx_3) && PyTuple_GET_SIZE(__pyx_3) == 3) {
      __pyx_4 = PyTuple_GET_ITEM(__pyx_3, 0);
      Py_INCREF(__pyx_4);
      Py_DECREF(__pyx_v_arr);
      __pyx_v_arr = __pyx_4;
      __pyx_4 = 0;
      __pyx_1 = PyTuple_GET_ITEM(__pyx_3, 1);
      Py_INCREF(__pyx_1);
      Py_DECREF(__pyx_v_qlen);
      __pyx_v_qlen = __pyx_1;
      __pyx_1 = 0;
      __pyx_4 = PyTuple_GET_ITEM(__pyx_3, 2);
      Py_INCREF(__pyx_4);
      Py_DECREF(__pyx_v_slen);
      __pyx_v_slen = __pyx_4;
      __pyx_4 = 0;
      Py_DECREF(__pyx_3); __pyx_3 = 0;
    }
    else {
      __pyx_5 = PyObject_GetIter(__pyx_3); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      __pyx_4 = __Pyx_UnpackItem(__pyx_5); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
      Py_DECREF(__pyx_v_arr);
      __pyx_v_arr = __pyx_4;
      __pyx_4 = 0;
      __pyx_1 = __Pyx_UnpackItem(__pyx_5); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
      Py_DECREF(__pyx_v_qlen);
      __pyx_v_qlen = __pyx_1;
      __pyx_1 = 0;
      __pyx_4 = __Pyx_UnpackItem(__pyx_5); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
      Py_DECREF(__pyx_v_slen);
      __pyx_v_slen = __pyx_4;
      __pyx_4 = 0;
      if (__Pyx_EndUnpack(__pyx_5) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
      Py_DECREF(__pyx_5); __pyx_5 = 0;
    }

    /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":119
 * 
 *         arr, qlen, slen = _blast_array(fi, maxkeep)
 *         BLAST_TYPES[0] = 'S' + str(qlen)             # <<<<<<<<<<<<<< 
 *         BLAST_TYPES[1] = 'S' + str(slen)
 *     else:
 */
    __pyx_1 = PyTuple_New(1); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
    Py_INCREF(__pyx_v_qlen);
    PyTuple_SET_ITEM(__pyx_1, 0, __pyx_v_qlen);
    __pyx_4 = PyObject_CallObject(((PyObject*)&PyString_Type), __pyx_1); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_3 = PyNumber_Add(__pyx_n_S, __pyx_4); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __pyx_5 = __Pyx_GetName(__pyx_m, __pyx_n_BLAST_TYPES); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
    if (PyList_CheckExact(__pyx_5) && 0 <= 0 && 0 < PyList_GET_SIZE(__pyx_5)) {
      Py_DECREF(PyList_GET_ITEM(__pyx_5, 0)); Py_INCREF(__pyx_3);
      PyList_SET_ITEM(__pyx_5, 0, __pyx_3);
      } else {
      __pyx_1 = PyInt_FromLong(0); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
      if (PyObject_SetItem(__pyx_5, __pyx_1, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
      Py_DECREF(__pyx_1); __pyx_1 = 0;
    }
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;

    /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":120
 *         arr, qlen, slen = _blast_array(fi, maxkeep)
 *         BLAST_TYPES[0] = 'S' + str(qlen)
 *         BLAST_TYPES[1] = 'S' + str(slen)             # <<<<<<<<<<<<<< 
 *     else:
 *         arr = fi
 */
    __pyx_4 = PyTuple_New(1); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 120; goto __pyx_L1;}
    Py_INCREF(__pyx_v_slen);
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_v_slen);
    __pyx_3 = PyObject_CallObject(((PyObject*)&PyString_Type), __pyx_4); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 120; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __pyx_5 = PyNumber_Add(__pyx_n_S, __pyx_3); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 120; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_BLAST_TYPES); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 120; goto __pyx_L1;}
    if (PyList_CheckExact(__pyx_1) && 0 <= 1 && 1 < PyList_GET_SIZE(__pyx_1)) {
      Py_DECREF(PyList_GET_ITEM(__pyx_1, 1)); Py_INCREF(__pyx_5);
      PyList_SET_ITEM(__pyx_1, 1, __pyx_5);
      } else {
      __pyx_4 = PyInt_FromLong(1); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 120; goto __pyx_L1;}
      if (PyObject_SetItem(__pyx_1, __pyx_4, __pyx_5) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 120; goto __pyx_L1;}
      Py_DECREF(__pyx_4); __pyx_4 = 0;
    }
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    goto __pyx_L2;
  }
  /*else*/ {

    /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":122
 *         BLAST_TYPES[1] = 'S' + str(slen)
 *     else:
 *         arr = fi             # <<<<<<<<<<<<<< 
 *     if not len(arr):
 *         return []
 */
    Py_INCREF(__pyx_v_fi);
    Py_DECREF(__pyx_v_arr);
    __pyx_v_arr = __pyx_v_fi;
  }
  __pyx_L2:;

  /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":123
 *     else:
 *         arr = fi
 *     if not len(arr):             # <<<<<<<<<<<<<< 
 *         return []
 * 
 */
  __pyx_7 = PyObject_Length(__pyx_v_arr); if (unlikely(__pyx_7 == -1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 123; goto __pyx_L1;}
  __pyx_2 = (!__pyx_7);
  if (__pyx_2) {

    /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":124
 *         arr = fi
 *     if not len(arr):
 *         return []             # <<<<<<<<<<<<<< 
 * 
 *     if type(arr) == numpy.recarray:
 */
    __pyx_3 = PyList_New(0); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 124; goto __pyx_L1;}
    __pyx_r = __pyx_3;
    __pyx_3 = 0;
    goto __pyx_L0;
    goto __pyx_L5;
  }
  __pyx_L5:;

  /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":126
 *         return []
 * 
 *     if type(arr) == numpy.recarray:             # <<<<<<<<<<<<<< 
 *         ra = arr
 *     else:
 */
  __pyx_5 = PyTuple_New(1); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 126; goto __pyx_L1;}
  Py_INCREF(__pyx_v_arr);
  PyTuple_SET_ITEM(__pyx_5, 0, __pyx_v_arr);
  __pyx_1 = PyObject_CallObject(((PyObject*)&PyType_Type), __pyx_5); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 126; goto __pyx_L1;}
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  __pyx_4 = __Pyx_GetName(__pyx_m, __pyx_n_numpy); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 126; goto __pyx_L1;}
  __pyx_3 = PyObject_GetAttr(__pyx_4, __pyx_n_recarray); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 126; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_5 = PyObject_RichCompare(__pyx_1, __pyx_3, Py_EQ); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 126; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_6 = __Pyx_PyObject_IsTrue(__pyx_5); if (unlikely(__pyx_6 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 126; goto __pyx_L1;}
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  if (__pyx_6) {

    /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":127
 * 
 *     if type(arr) == numpy.recarray:
 *         ra = arr             # <<<<<<<<<<<<<< 
 *     else:
 *         ra = numpy.rec.array(arr, names=BLAST_NAMES, formats=BLAST_TYPES)
 */
    Py_INCREF(__pyx_v_arr);
    Py_DECREF(__pyx_v_ra);
    __pyx_v_ra = __pyx_v_arr;
    goto __pyx_L6;
  }
  /*else*/ {

    /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":129
 *         ra = arr
 *     else:
 *         ra = numpy.rec.array(arr, names=BLAST_NAMES, formats=BLAST_TYPES)             # <<<<<<<<<<<<<< 
 * 
 *     if dopickle and file_name: ra.dump(file_name)
 */
    __pyx_4 = __Pyx_GetName(__pyx_m, __pyx_n_numpy); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 129; goto __pyx_L1;}
    __pyx_1 = PyObject_GetAttr(__pyx_4, __pyx_n_rec); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 129; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __pyx_3 = PyObject_GetAttr(__pyx_1, __pyx_n_array); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 129; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_5 = PyTuple_New(1); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 129; goto __pyx_L1;}
    Py_INCREF(__pyx_v_arr);
    PyTuple_SET_ITEM(__pyx_5, 0, __pyx_v_arr);
    __pyx_4 = PyDict_New(); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 129; goto __pyx_L1;}
    __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_BLAST_NAMES); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 129; goto __pyx_L1;}
    if (PyDict_SetItem(__pyx_4, __pyx_n_names, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 129; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_BLAST_TYPES); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 129; goto __pyx_L1;}
    if (PyDict_SetItem(__pyx_4, __pyx_n_formats, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 129; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_1 = PyEval_CallObjectWithKeywords(__pyx_3, __pyx_5, __pyx_4); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 129; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_v_ra);
    __pyx_v_ra = __pyx_1;
    __pyx_1 = 0;
  }
  __pyx_L6:;

  /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":131
 *         ra = numpy.rec.array(arr, names=BLAST_NAMES, formats=BLAST_TYPES)
 * 
 *     if dopickle and file_name: ra.dump(file_name)             # <<<<<<<<<<<<<< 
 *     # hit_rank of 0 is the best hit
 *     if best_hit: ra = ra[ra['hit_rank'] == 0]
 */
  __pyx_3 = __pyx_v_dopickle;
  Py_INCREF(__pyx_3);
  __pyx_2 = __Pyx_PyObject_IsTrue(__pyx_3); if (unlikely(__pyx_2 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
  if (__pyx_2) {
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_3 = __pyx_v_file_name;
    Py_INCREF(__pyx_3);
  }
  __pyx_6 = __Pyx_PyObject_IsTrue(__pyx_3); if (unlikely(__pyx_6 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  if (__pyx_6) {
    __pyx_5 = PyObject_GetAttr(__pyx_v_ra, __pyx_n_dump); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(1); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
    Py_INCREF(__pyx_v_file_name);
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_v_file_name);
    __pyx_1 = PyObject_CallObject(__pyx_5, __pyx_4); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    goto __pyx_L7;
  }
  __pyx_L7:;

  /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":133
 *     if dopickle and file_name: ra.dump(file_name)
 *     # hit_rank of 0 is the best hit
 *     if best_hit: ra = ra[ra['hit_rank'] == 0]             # <<<<<<<<<<<<<< 
 *     return ra
 *  
 */
  __pyx_2 = __Pyx_PyObject_IsTrue(__pyx_v_best_hit); if (unlikely(__pyx_2 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 133; goto __pyx_L1;}
  if (__pyx_2) {
    __pyx_3 = PyObject_GetItem(__pyx_v_ra, __pyx_n_hit_rank); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 133; goto __pyx_L1;}
    __pyx_5 = PyObject_RichCompare(__pyx_3, __pyx_num_0, Py_EQ); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 133; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_4 = PyObject_GetItem(__pyx_v_ra, __pyx_5); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 133; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    Py_DECREF(__pyx_v_ra);
    __pyx_v_ra = __pyx_4;
    __pyx_4 = 0;
    goto __pyx_L8;
  }
  __pyx_L8:;

  /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":134
 *     # hit_rank of 0 is the best hit
 *     if best_hit: ra = ra[ra['hit_rank'] == 0]
 *     return ra             # <<<<<<<<<<<<<< 
 *  
 * 
 */
  Py_INCREF(__pyx_v_ra);
  __pyx_r = __pyx_v_ra;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("blast_misc.blast_array");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF(__pyx_v_file_name);
  Py_DECREF(__pyx_v_arr);
  Py_DECREF(__pyx_v_qlen);
  Py_DECREF(__pyx_v_slen);
  Py_DECREF(__pyx_v_ra);
  Py_DECREF(__pyx_v_fi);
  Py_DECREF(__pyx_v_dopickle);
  Py_DECREF(__pyx_v_best_hit);
  Py_DECREF(__pyx_v_maxkeep);
  return __pyx_r;
}

/* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":137
 *  
 * 
 * def order_from_blast_list(*args):             # <<<<<<<<<<<<<< 
 *     """ args is a list of blast filenames
 *     not yet implemented """
 */

static char __pyx_k49[] = "r";

static PyObject *__pyx_pf_10blast_misc_order_from_blast_list(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_10blast_misc_order_from_blast_list[] = " args is a list of blast filenames\n    not yet implemented ";
static PyObject *__pyx_pf_10blast_misc_order_from_blast_list(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_args = 0;
  int __pyx_v_qlen;
  int __pyx_v_slen;
  int __pyx_v_hlen;
  int __pyx_v_nmiss;
  int __pyx_v_ngap;
  int __pyx_v_qstart;
  int __pyx_v_qstop;
  int __pyx_v_sstart;
  int __pyx_v_sstop;
  int __pyx_v_icol;
  float __pyx_v_pct;
  float __pyx_v_evalue;
  float __pyx_v_bit;
  char __pyx_v_qname[128];
  char __pyx_v_sname[128];
  FILE *__pyx_v_fh;
  PyObject *__pyx_v_f;
  PyObject *__pyx_r;
  Py_ssize_t __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  char *__pyx_4;
  int __pyx_5;
  static char *__pyx_argnames[] = {0};
  if (__Pyx_GetStarArgs(&__pyx_args, &__pyx_kwds, __pyx_argnames, 0, &__pyx_v_args, 0, 0) < 0) return NULL;
  if (unlikely(!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames))) {
    Py_XDECREF(__pyx_args);
    Py_XDECREF(__pyx_kwds);
    Py_XDECREF(__pyx_v_args);
    return NULL;
  }
  __pyx_v_f = Py_None; Py_INCREF(Py_None);

  /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":140
 *     """ args is a list of blast filenames
 *     not yet implemented """
 *     cdef int qlen = 8, slen = 8, hlen, nmiss, ngap, qstart, qstop, sstart, sstop, icol = 0             # <<<<<<<<<<<<<< 
 *     cdef float pct = 0.0, evalue = 0.0, bit = 0.0
 *     cdef char qname[128], sname[128]
 */
  __pyx_v_qlen = 8;

  __pyx_v_slen = 8;

  __pyx_v_icol = 0;


  /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":141
 *     not yet implemented """
 *     cdef int qlen = 8, slen = 8, hlen, nmiss, ngap, qstart, qstop, sstart, sstop, icol = 0
 *     cdef float pct = 0.0, evalue = 0.0, bit = 0.0             # <<<<<<<<<<<<<< 
 *     cdef char qname[128], sname[128]
 *     cdef FILE *fh
 */
  __pyx_v_pct = 0.0;

  __pyx_v_evalue = 0.0;

  __pyx_v_bit = 0.0;


  /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":144
 *     cdef char qname[128], sname[128]
 *     cdef FILE *fh
 *     for f in args:             # <<<<<<<<<<<<<< 
 *         fh = fopen(f, "r")
 *         while fscanf(fh, blast_format, qname, sname, &pct, &hlen, &nmiss, &ngap, &qstart, &qstop, &sstart, &sstop, &evalue, &bit ) != EOF:
 */
  if (PyList_CheckExact(__pyx_v_args)) { __pyx_1 = 0; __pyx_2 = __pyx_v_args; Py_INCREF(__pyx_2); }
  else { __pyx_2 = PyObject_GetIter(__pyx_v_args); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 144; goto __pyx_L1;} }
  for (;;) {
    if (PyList_CheckExact(__pyx_2)) { if (__pyx_1 >= PyList_GET_SIZE(__pyx_2)) break; __pyx_3 = PyList_GET_ITEM(__pyx_2, __pyx_1++); Py_INCREF(__pyx_3); }
    else {
      __pyx_3 = PyIter_Next(__pyx_2);
      if (!__pyx_3) {
        break;
      }
    }
    Py_DECREF(__pyx_v_f);
    __pyx_v_f = __pyx_3;
    __pyx_3 = 0;

    /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":145
 *     cdef FILE *fh
 *     for f in args:
 *         fh = fopen(f, "r")             # <<<<<<<<<<<<<< 
 *         while fscanf(fh, blast_format, qname, sname, &pct, &hlen, &nmiss, &ngap, &qstart, &qstop, &sstart, &sstop, &evalue, &bit ) != EOF:
 *            pass 
 */
    __pyx_4 = PyString_AsString(__pyx_v_f); if (unlikely((!__pyx_4) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 145; goto __pyx_L1;}
    __pyx_v_fh = fopen(__pyx_4,__pyx_k49);

    /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":146
 *     for f in args:
 *         fh = fopen(f, "r")
 *         while fscanf(fh, blast_format, qname, sname, &pct, &hlen, &nmiss, &ngap, &qstart, &qstop, &sstart, &sstop, &evalue, &bit ) != EOF:             # <<<<<<<<<<<<<< 
 *            pass 
 *                     
 */
    while (1) {
      __pyx_5 = (fscanf(__pyx_v_fh,__pyx_v_10blast_misc_blast_format,__pyx_v_qname,__pyx_v_sname,(&__pyx_v_pct),(&__pyx_v_hlen),(&__pyx_v_nmiss),(&__pyx_v_ngap),(&__pyx_v_qstart),(&__pyx_v_qstop),(&__pyx_v_sstart),(&__pyx_v_sstop),(&__pyx_v_evalue),(&__pyx_v_bit)) != EOF);
      if (!__pyx_5) break;
    }

    /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":149
 *            pass 
 *                     
 *         fclose(fh)             # <<<<<<<<<<<<<< 
 */
    fclose(__pyx_v_fh);
  }
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("blast_misc.order_from_blast_list");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_XDECREF(__pyx_v_args);
  Py_DECREF(__pyx_v_f);
  Py_XDECREF(__pyx_args);
  Py_XDECREF(__pyx_kwds);
  return __pyx_r;
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n_BLAST_NAMES, "BLAST_NAMES"},
  {&__pyx_n_BLAST_TYPES, "BLAST_TYPES"},
  {&__pyx_n_S, "S"},
  {&__pyx_n_S8, "S8"},
  {&__pyx_n__, "_"},
  {&__pyx_n__blast_array, "_blast_array"},
  {&__pyx_n_array, "array"},
  {&__pyx_n_b1, "b1"},
  {&__pyx_n_collections, "collections"},
  {&__pyx_n_defaultdict, "defaultdict"},
  {&__pyx_n_dump, "dump"},
  {&__pyx_n_dup, "dup"},
  {&__pyx_n_eval, "eval"},
  {&__pyx_n_exists, "exists"},
  {&__pyx_n_f4, "f4"},
  {&__pyx_n_f8, "f8"},
  {&__pyx_n_formats, "formats"},
  {&__pyx_n_hit_length, "hit_length"},
  {&__pyx_n_hit_rank, "hit_rank"},
  {&__pyx_n_i4, "i4"},
  {&__pyx_n_i8, "i8"},
  {&__pyx_n_itemgetter, "itemgetter"},
  {&__pyx_n_key, "key"},
  {&__pyx_n_load, "load"},
  {&__pyx_n_n_gaps, "n_gaps"},
  {&__pyx_n_n_mismatch, "n_mismatch"},
  {&__pyx_n_names, "names"},
  {&__pyx_n_numpy, "numpy"},
  {&__pyx_n_operator, "operator"},
  {&__pyx_n_os, "os"},
  {&__pyx_n_path, "path"},
  {&__pyx_n_percent_id, "percent_id"},
  {&__pyx_n_qstart, "qstart"},
  {&__pyx_n_qstop, "qstop"},
  {&__pyx_n_query, "query"},
  {&__pyx_n_rec, "rec"},
  {&__pyx_n_recarray, "recarray"},
  {&__pyx_n_score, "score"},
  {&__pyx_n_sorted, "sorted"},
  {&__pyx_n_sstart, "sstart"},
  {&__pyx_n_sstop, "sstop"},
  {&__pyx_n_subject, "subject"},
  {0, 0}
};

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_k42p, __pyx_k42, sizeof(__pyx_k42), 0},
  {0, 0, 0, 0}
};

static struct PyMethodDef __pyx_methods[] = {
  {"pyaddlocs", (PyCFunction)__pyx_pf_10blast_misc_pyaddlocs, METH_VARARGS|METH_KEYWORDS, __pyx_doc_10blast_misc_pyaddlocs},
  {"pylocslist", (PyCFunction)__pyx_pf_10blast_misc_pylocslist, METH_VARARGS|METH_KEYWORDS, __pyx_doc_10blast_misc_pylocslist},
  {"_blast_array", (PyCFunction)__pyx_pf_10blast_misc__blast_array, METH_VARARGS|METH_KEYWORDS, 0},
  {"blast_array", (PyCFunction)__pyx_pf_10blast_misc_blast_array, METH_VARARGS|METH_KEYWORDS, 0},
  {"order_from_blast_list", (PyCFunction)__pyx_pf_10blast_misc_order_from_blast_list, METH_VARARGS|METH_KEYWORDS, __pyx_doc_10blast_misc_order_from_blast_list},
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initblast_misc(void); /*proto*/
PyMODINIT_FUNC initblast_misc(void) {
  PyObject *__pyx_1 = 0;
  /*--- Libary function declarations ---*/
  __pyx_init_filenames();
  /*--- Module creation code ---*/
  __pyx_m = Py_InitModule4("blast_misc", __pyx_methods, __pyx_mdoc, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  /*--- Intern code ---*/
  __pyx_num_1 = PyInt_FromLong(1); if (unlikely(!__pyx_num_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  __pyx_num_6 = PyInt_FromLong(6); if (unlikely(!__pyx_num_6)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  __pyx_num_10 = PyInt_FromLong(10); if (unlikely(!__pyx_num_10)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  __pyx_num_0 = PyInt_FromLong(0); if (unlikely(!__pyx_num_0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  /*--- String init code ---*/
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  /*--- Builtin init code ---*/
  __pyx_builtin_sorted = __Pyx_GetName(__pyx_b, __pyx_n_sorted); if (!__pyx_builtin_sorted) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
  /*--- Global init code ---*/
  /*--- Function export code ---*/
  /*--- Function import code ---*/
  /*--- Type init code ---*/
  /*--- Type import code ---*/
  /*--- Execution code ---*/

  /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":9
 * """
 * 
 * import operator             # <<<<<<<<<<<<<< 
 * import collections
 * import os
 */
  __pyx_1 = __Pyx_Import(__pyx_n_operator, 0); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_operator, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":10
 * 
 * import operator 
 * import collections             # <<<<<<<<<<<<<< 
 * import os
 * import numpy 
 */
  __pyx_1 = __Pyx_Import(__pyx_n_collections, 0); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 10; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_collections, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 10; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":11
 * import operator 
 * import collections
 * import os             # <<<<<<<<<<<<<< 
 * import numpy 
 * 
 */
  __pyx_1 = __Pyx_Import(__pyx_n_os, 0); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 11; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_os, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 11; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":12
 * import collections
 * import os
 * import numpy             # <<<<<<<<<<<<<< 
 * 
 * 
 */
  __pyx_1 = __Pyx_Import(__pyx_n_numpy, 0); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 12; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_numpy, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 12; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":16
 * 
 * BLAST_NAMES = ['query', 'subject', 'percent_id', 'hit_length', 'n_mismatch', \
 *     'n_gaps', 'qstart', 'qstop', 'sstart', 'sstop', 'eval', 'score','hit_rank','dup']             # <<<<<<<<<<<<<< 
 * 
 * BLAST_TYPES = ['S8', 'S8', 'f4', 'i4', 'i4', 'i4', 'i8', 'i8', 'i8', 'i8', 'f8', 'f8', 'i4', 'b1']
 */
  __pyx_1 = PyList_New(14); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; goto __pyx_L1;}
  Py_INCREF(__pyx_n_query);
  PyList_SET_ITEM(__pyx_1, 0, __pyx_n_query);
  Py_INCREF(__pyx_n_subject);
  PyList_SET_ITEM(__pyx_1, 1, __pyx_n_subject);
  Py_INCREF(__pyx_n_percent_id);
  PyList_SET_ITEM(__pyx_1, 2, __pyx_n_percent_id);
  Py_INCREF(__pyx_n_hit_length);
  PyList_SET_ITEM(__pyx_1, 3, __pyx_n_hit_length);
  Py_INCREF(__pyx_n_n_mismatch);
  PyList_SET_ITEM(__pyx_1, 4, __pyx_n_n_mismatch);
  Py_INCREF(__pyx_n_n_gaps);
  PyList_SET_ITEM(__pyx_1, 5, __pyx_n_n_gaps);
  Py_INCREF(__pyx_n_qstart);
  PyList_SET_ITEM(__pyx_1, 6, __pyx_n_qstart);
  Py_INCREF(__pyx_n_qstop);
  PyList_SET_ITEM(__pyx_1, 7, __pyx_n_qstop);
  Py_INCREF(__pyx_n_sstart);
  PyList_SET_ITEM(__pyx_1, 8, __pyx_n_sstart);
  Py_INCREF(__pyx_n_sstop);
  PyList_SET_ITEM(__pyx_1, 9, __pyx_n_sstop);
  Py_INCREF(__pyx_n_eval);
  PyList_SET_ITEM(__pyx_1, 10, __pyx_n_eval);
  Py_INCREF(__pyx_n_score);
  PyList_SET_ITEM(__pyx_1, 11, __pyx_n_score);
  Py_INCREF(__pyx_n_hit_rank);
  PyList_SET_ITEM(__pyx_1, 12, __pyx_n_hit_rank);
  Py_INCREF(__pyx_n_dup);
  PyList_SET_ITEM(__pyx_1, 13, __pyx_n_dup);
  if (PyObject_SetAttr(__pyx_m, __pyx_n_BLAST_NAMES, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":18
 *     'n_gaps', 'qstart', 'qstop', 'sstart', 'sstop', 'eval', 'score','hit_rank','dup']
 * 
 * BLAST_TYPES = ['S8', 'S8', 'f4', 'i4', 'i4', 'i4', 'i8', 'i8', 'i8', 'i8', 'f8', 'f8', 'i4', 'b1']             # <<<<<<<<<<<<<< 
 * 
 * 
 */
  __pyx_1 = PyList_New(14); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 18; goto __pyx_L1;}
  Py_INCREF(__pyx_n_S8);
  PyList_SET_ITEM(__pyx_1, 0, __pyx_n_S8);
  Py_INCREF(__pyx_n_S8);
  PyList_SET_ITEM(__pyx_1, 1, __pyx_n_S8);
  Py_INCREF(__pyx_n_f4);
  PyList_SET_ITEM(__pyx_1, 2, __pyx_n_f4);
  Py_INCREF(__pyx_n_i4);
  PyList_SET_ITEM(__pyx_1, 3, __pyx_n_i4);
  Py_INCREF(__pyx_n_i4);
  PyList_SET_ITEM(__pyx_1, 4, __pyx_n_i4);
  Py_INCREF(__pyx_n_i4);
  PyList_SET_ITEM(__pyx_1, 5, __pyx_n_i4);
  Py_INCREF(__pyx_n_i8);
  PyList_SET_ITEM(__pyx_1, 6, __pyx_n_i8);
  Py_INCREF(__pyx_n_i8);
  PyList_SET_ITEM(__pyx_1, 7, __pyx_n_i8);
  Py_INCREF(__pyx_n_i8);
  PyList_SET_ITEM(__pyx_1, 8, __pyx_n_i8);
  Py_INCREF(__pyx_n_i8);
  PyList_SET_ITEM(__pyx_1, 9, __pyx_n_i8);
  Py_INCREF(__pyx_n_f8);
  PyList_SET_ITEM(__pyx_1, 10, __pyx_n_f8);
  Py_INCREF(__pyx_n_f8);
  PyList_SET_ITEM(__pyx_1, 11, __pyx_n_f8);
  Py_INCREF(__pyx_n_i4);
  PyList_SET_ITEM(__pyx_1, 12, __pyx_n_i4);
  Py_INCREF(__pyx_n_b1);
  PyList_SET_ITEM(__pyx_1, 13, __pyx_n_b1);
  if (PyObject_SetAttr(__pyx_m, __pyx_n_BLAST_TYPES, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 18; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":50
 *     int add_locs(char *, char *)
 * 
 * cdef char * blast_format = "%s\t%s\t%f\t%d\t%d\t%d\t%d\t%d\t%d\t%d\t%e\t%f\n"             # <<<<<<<<<<<<<< 
 * 
 * #cdef inline int set_list(object PyList, int idx, object obj) except -1:
 */
  __pyx_v_10blast_misc_blast_format = __pyx_k33;


  /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":57
 * 
 * 
 * def pyaddlocs(inname, outname=None):             # <<<<<<<<<<<<<< 
 *     """ take a file name and add the global locs 
 *     inplace if outname==None, or to a new file (outname).
 */
  Py_INCREF(Py_None);
  __pyx_k34 = Py_None;

  /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":106
 * 
 * 
 * def blast_array(fi, dopickle=1, best_hit=1, maxkeep=6):             # <<<<<<<<<<<<<< 
 *     file_name = 0
 *     if not isinstance(fi, list) and type(fi) != numpy.recarray:
 */
  Py_INCREF(__pyx_num_1);
  __pyx_k35 = __pyx_num_1;
  Py_INCREF(__pyx_num_1);
  __pyx_k36 = __pyx_num_1;
  Py_INCREF(__pyx_num_6);
  __pyx_k37 = __pyx_num_6;

  /* "/opt/src/bpbio/blasttools/blast_misc/blast_misc.pyx":137
 *  
 * 
 * def order_from_blast_list(*args):             # <<<<<<<<<<<<<< 
 *     """ args is a list of blast filenames
 *     not yet implemented """
 */
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("blast_misc");
}

static char *__pyx_filenames[] = {
  "blast_misc.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static int __Pyx_GetStarArgs(
    PyObject **args, 
    PyObject **kwds,
    char *kwd_list[], 
    Py_ssize_t nargs,
    PyObject **args2, 
    PyObject **kwds2,
    char rqd_kwds[])
{
    PyObject *x = 0, *args1 = 0, *kwds1 = 0;
    int i;
    char **p;
    
    if (args2)
        *args2 = 0;
    if (kwds2)
        *kwds2 = 0;
    
    if (args2) {
        args1 = PyTuple_GetSlice(*args, 0, nargs);
        if (!args1)
            goto bad;
        *args2 = PyTuple_GetSlice(*args, nargs, PyTuple_GET_SIZE(*args));
        if (!*args2)
            goto bad;
    }
    else if (PyTuple_GET_SIZE(*args) > nargs) {
        int m = nargs;
        int n = PyTuple_GET_SIZE(*args);
        PyErr_Format(PyExc_TypeError,
            "function takes at most %d positional arguments (%d given)",
                m, n);
        goto bad;
    }
    else {
        args1 = *args;
        Py_INCREF(args1);
    }
    
    if (rqd_kwds && !*kwds)
            for (i = 0, p = kwd_list; *p; i++, p++)
                if (rqd_kwds[i])
                    goto missing_kwarg;
    
    if (kwds2) {
        if (*kwds) {
            kwds1 = PyDict_New();
            if (!kwds1)
                goto bad;
            *kwds2 = PyDict_Copy(*kwds);
            if (!*kwds2)
                goto bad;
            for (i = 0, p = kwd_list; *p; i++, p++) {
                x = PyDict_GetItemString(*kwds, *p);
                if (x) {
                    if (PyDict_SetItemString(kwds1, *p, x) < 0)
                        goto bad;
                    if (PyDict_DelItemString(*kwds2, *p) < 0)
                        goto bad;
                }
                else if (rqd_kwds && rqd_kwds[i])
                    goto missing_kwarg;
            }
        }
        else {
            *kwds2 = PyDict_New();
            if (!*kwds2)
                goto bad;
        }
    }
    else {
        kwds1 = *kwds;
        Py_XINCREF(kwds1);
        if (rqd_kwds && *kwds)
            for (i = 0, p = kwd_list; *p; i++, p++)
                if (rqd_kwds[i] && !PyDict_GetItemString(*kwds, *p))
                        goto missing_kwarg;
    }
    
    *args = args1;
    *kwds = kwds1;
    return 0;
missing_kwarg:
    PyErr_Format(PyExc_TypeError,
        "required keyword argument '%s' is missing", *p);
bad:
    Py_XDECREF(args1);
    Py_XDECREF(kwds1);
    if (args2) {
        Py_XDECREF(*args2);
    }
    if (kwds2) {
        Py_XDECREF(*kwds2);
    }
    return -1;
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

static PyObject *__Pyx_GetStdout(void) {
    PyObject *f = PySys_GetObject("stdout");
    if (!f) {
        PyErr_SetString(PyExc_RuntimeError, "lost sys.stdout");
    }
    return f;
}

static int __Pyx_PrintItem(PyObject *v) {
    PyObject *f;
    
    if (!(f = __Pyx_GetStdout()))
        return -1;
    if (PyFile_SoftSpace(f, 1)) {
        if (PyFile_WriteString(" ", f) < 0)
            return -1;
    }
    if (PyFile_WriteObject(v, f, Py_PRINT_RAW) < 0)
        return -1;
    if (PyString_Check(v)) {
        char *s = PyString_AsString(v);
        Py_ssize_t len = PyString_Size(v);
        if (len > 0 &&
            isspace(Py_CHARMASK(s[len-1])) &&
            s[len-1] != ' ')
                PyFile_SoftSpace(f, 0);
    }
    return 0;
}

static int __Pyx_PrintNewline(void) {
    PyObject *f;
    
    if (!(f = __Pyx_GetStdout()))
        return -1;
    if (PyFile_WriteString("\n", f) < 0)
        return -1;
    PyFile_SoftSpace(f, 0);
    return 0;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static void __Pyx_UnpackError(void) {
    PyErr_SetString(PyExc_ValueError, "unpack sequence of wrong size");
}

static PyObject *__Pyx_UnpackItem(PyObject *iter) {
    PyObject *item;
    if (!(item = PyIter_Next(iter))) {
        if (!PyErr_Occurred())
            __Pyx_UnpackError();
    }
    return item;
}

static int __Pyx_EndUnpack(PyObject *iter) {
    PyObject *item;
    if ((item = PyIter_Next(iter))) {
        Py_DECREF(item);
        __Pyx_UnpackError();
        return -1;
    }
    else if (!PyErr_Occurred())
        return 0;
    else
        return -1;
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        if (t->is_unicode) {
            *t->p = PyUnicode_DecodeUTF8(t->s, t->n - 1, NULL);
        } else {
            *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        }
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}

/* Type Conversion Functions */

static INLINE Py_ssize_t __pyx_PyIndex_AsSsize_t(PyObject* b) {
  Py_ssize_t ival;
  PyObject* x = PyNumber_Index(b);
  if (!x) return -1;
  ival = PyInt_AsSsize_t(x);
  Py_DECREF(x);
  return ival;
}

static INLINE int __Pyx_PyObject_IsTrue(PyObject* x) {
   if (x == Py_True) return 1;
   else if (x == Py_False) return 0;
   else return PyObject_IsTrue(x);
}

static INLINE PY_LONG_LONG __pyx_PyInt_AsLongLong(PyObject* x) {
    if (PyInt_CheckExact(x)) {
        return PyInt_AS_LONG(x);
    }
    else if (PyLong_CheckExact(x)) {
        return PyLong_AsLongLong(x);
    }
    else {
        PyObject* tmp = PyNumber_Int(x); if (!tmp) return (PY_LONG_LONG)-1;
        PY_LONG_LONG val = __pyx_PyInt_AsLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE unsigned PY_LONG_LONG __pyx_PyInt_AsUnsignedLongLong(PyObject* x) {
    if (PyInt_CheckExact(x)) {
        long val = PyInt_AS_LONG(x);
        if (unlikely(val < 0)) {
            PyErr_SetString(PyExc_TypeError, "Negative assignment to unsigned type.");
            return (unsigned PY_LONG_LONG)-1;
        }
        return val;
    }
    else if (PyLong_CheckExact(x)) {
        return PyLong_AsUnsignedLongLong(x);
    }
    else {
        PyObject* tmp = PyNumber_Int(x); if (!tmp) return (PY_LONG_LONG)-1;
        PY_LONG_LONG val = __pyx_PyInt_AsUnsignedLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}


static INLINE unsigned char __pyx_PyInt_unsigned_char(PyObject* x) {
    if (sizeof(unsigned char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        unsigned char val = (unsigned char)long_val;
        if (unlikely((val != long_val)  || (long_val < 0))) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to unsigned char");
            return (unsigned char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE unsigned short __pyx_PyInt_unsigned_short(PyObject* x) {
    if (sizeof(unsigned short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        unsigned short val = (unsigned short)long_val;
        if (unlikely((val != long_val)  || (long_val < 0))) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to unsigned short");
            return (unsigned short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE char __pyx_PyInt_char(PyObject* x) {
    if (sizeof(char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        char val = (char)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to char");
            return (char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE short __pyx_PyInt_short(PyObject* x) {
    if (sizeof(short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        short val = (short)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to short");
            return (short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE int __pyx_PyInt_int(PyObject* x) {
    if (sizeof(int) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        int val = (int)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to int");
            return (int)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE long __pyx_PyInt_long(PyObject* x) {
    if (sizeof(long) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        long val = (long)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to long");
            return (long)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed char __pyx_PyInt_signed_char(PyObject* x) {
    if (sizeof(signed char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed char val = (signed char)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed char");
            return (signed char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed short __pyx_PyInt_signed_short(PyObject* x) {
    if (sizeof(signed short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed short val = (signed short)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed short");
            return (signed short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed int __pyx_PyInt_signed_int(PyObject* x) {
    if (sizeof(signed int) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed int val = (signed int)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed int");
            return (signed int)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed long __pyx_PyInt_signed_long(PyObject* x) {
    if (sizeof(signed long) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed long val = (signed long)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed long");
            return (signed long)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE long double __pyx_PyInt_long_double(PyObject* x) {
    if (sizeof(long double) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        long double val = (long double)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to long double");
            return (long double)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}
