
PROG=dagchainer

#CCFLAGS=-Wno-deprecated
#CCFLAGS=-O3 -s -fomit-frame-pointer -msse2 -Wno-deprecated
CCFLAGS=-O3 -s -fomit-frame-pointer -Wno-deprecated
all: 
	g++ -o ${PROG} dagchainer.cpp ${CCFLAGS}


