/* Generated by Cython 0.9.6.14 on Fri May  9 10:08:46 2008 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)   PyInt_AsLong(o)
  #define PyNumber_Index(o)    PyNumber_Int(o)
  #define PyIndex_Check(o)     PyNumber_Check(o)
#endif
#if PY_VERSION_HEX < 0x02040000
  #define METH_COEXIST 0
#endif
#ifndef __stdcall
  #define __stdcall
#endif
#ifndef __cdecl
  #define __cdecl
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>
#include "stdlib.h"


#ifdef __GNUC__
#define INLINE __inline__
#elif _WIN32
#define INLINE __inline
#else
#define INLINE 
#endif

typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n; int is_unicode;} __Pyx_StringTabEntry; /*proto*/



static int __pyx_skip_dispatch = 0;


/* Type Conversion Predeclarations */

#define __Pyx_PyBool_FromLong(b) ((b) ? (Py_INCREF(Py_True), Py_True) : (Py_INCREF(Py_False), Py_False))
static INLINE int __Pyx_PyObject_IsTrue(PyObject* x);
static INLINE PY_LONG_LONG __pyx_PyInt_AsLongLong(PyObject* x);
static INLINE unsigned PY_LONG_LONG __pyx_PyInt_AsUnsignedLongLong(PyObject* x);
static INLINE Py_ssize_t __pyx_PyIndex_AsSsize_t(PyObject* b);

#define __pyx_PyInt_AsLong(x) (PyInt_CheckExact(x) ? PyInt_AS_LONG(x) : PyInt_AsLong(x))
#define __pyx_PyFloat_AsDouble(x) (PyFloat_CheckExact(x) ? PyFloat_AS_DOUBLE(x) : PyFloat_AsDouble(x))

static INLINE unsigned char __pyx_PyInt_unsigned_char(PyObject* x);
static INLINE unsigned short __pyx_PyInt_unsigned_short(PyObject* x);
static INLINE char __pyx_PyInt_char(PyObject* x);
static INLINE short __pyx_PyInt_short(PyObject* x);
static INLINE int __pyx_PyInt_int(PyObject* x);
static INLINE long __pyx_PyInt_long(PyObject* x);
static INLINE signed char __pyx_PyInt_signed_char(PyObject* x);
static INLINE signed short __pyx_PyInt_signed_short(PyObject* x);
static INLINE signed int __pyx_PyInt_signed_int(PyObject* x);
static INLINE signed long __pyx_PyInt_signed_long(PyObject* x);
static INLINE long double __pyx_PyInt_long_double(PyObject* x);
#ifdef __GNUC__
/* Test for GCC > 2.95 */
#if __GNUC__ > 2 ||               (__GNUC__ == 2 && (__GNUC_MINOR__ > 95)) 
#define likely(x)   __builtin_expect(!!(x), 1)
#define unlikely(x) __builtin_expect(!!(x), 0)
#else /* __GNUC__ > 2 ... */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ > 2 ... */
#else /* __GNUC__ */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ */
    
static PyObject *__pyx_m;
static PyObject *__pyx_b;
static PyObject *__pyx_empty_tuple;
static int __pyx_lineno;
static int __pyx_clineno = 0;
static char * __pyx_cfilenm= __FILE__;
static char *__pyx_filename;
static char **__pyx_f;

static char __pyx_mdoc[] = "\nThis is a fast, cython implementation of this:\nhttp://aspn.activestate.com/ASPN/Cookbook/Python/Recipe/572156\n\nto allow fast searching for similar sequences. \n\nprovides:\n    function edit_distance: which takes 2 strings, and a\n                maximum distance (int) and returns the damerau-levenshtein distance\n                between those strings:\n\n    class BKtree: takes a list of [\"words\", \"and\", \"creates\", \"a\", \"search\", \"tree\"]\n                  so that it can be searched for any words within dist\n                  of a given word:\n            >>> tree.find(\"asd\", 1)\n            [\"and\"]\n            >>> tree.find(\"asd\", 2)\n            [\"and\", \"a\"]\n";

static INLINE void __Pyx_RaiseArgtupleTooLong(Py_ssize_t num_expected, Py_ssize_t num_found); /*proto*/

static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type); /*proto*/

static inline PyObject* __Pyx_PyObject_Append(PyObject* L, PyObject* x) {
    if (likely(PyList_CheckExact(L))) {
        if (PyList_Append(L, x) < 0) return NULL;
        Py_INCREF(Py_None);
        return Py_None; // this is just to have an accurate signature
    }
    else {
        return PyObject_CallMethod(L, "append", "(O)", x);
    }
}

static void __Pyx_WriteUnraisable(char *name); /*proto*/

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations */

/* "/opt/src/bpbio/seqfind/seqfind.pyx":128
 *         return "<Word. {'word': '%s' }>" % self.word
 * 
 * cdef class BKTree:             # <<<<<<<<<<<<<< 
 *     """
 *     a simple http://en.wikipedia.org/wiki/BK-tree
 */

struct __pyx_obj_7seqfind_BKTree {
  PyObject_HEAD
  struct __pyx_vtabstruct_7seqfind_BKTree *__pyx_vtab;
  struct __pyx_obj_7seqfind_Word *root;
  PyObject *nodes;
};

/* "/opt/src/bpbio/seqfind/seqfind.pyx":116
 * 
 * 
 * cdef class Word:             # <<<<<<<<<<<<<< 
 *     cdef public char* word
 *     cdef public object info
 */

struct __pyx_obj_7seqfind_Word {
  PyObject_HEAD
  char *word;
  PyObject *info;
  int distance;
};


/* "/opt/src/bpbio/seqfind/seqfind.pyx":128
 *         return "<Word. {'word': '%s' }>" % self.word
 * 
 * cdef class BKTree:             # <<<<<<<<<<<<<< 
 *     """
 *     a simple http://en.wikipedia.org/wiki/BK-tree
 */

struct __pyx_vtabstruct_7seqfind_BKTree {
  PyObject *(*addNode)(struct __pyx_obj_7seqfind_BKTree *, struct __pyx_obj_7seqfind_Word *, struct __pyx_obj_7seqfind_Word *);
  PyObject *(*find)(struct __pyx_obj_7seqfind_BKTree *, char *, int);
  void (*_find)(struct __pyx_obj_7seqfind_BKTree *, struct __pyx_obj_7seqfind_Word *, struct __pyx_obj_7seqfind_Word *, int, PyObject *);
};
static struct __pyx_vtabstruct_7seqfind_BKTree *__pyx_vtabptr_7seqfind_BKTree;

static PyTypeObject *__pyx_ptype_7seqfind_Word = 0;
static PyTypeObject *__pyx_ptype_7seqfind_BKTree = 0;
static size_t __pyx_f_7seqfind_imin(int, int, int); /*proto*/
static int __pyx_f_7seqfind_edit_distance(char *, char *, int); /*proto*/


/* Implementation of seqfind */

static PyObject *__pyx_n_edit_distance;
static PyObject *__pyx_n___cinit__;
static PyObject *__pyx_n___repr__;
static PyObject *__pyx_n___init__;
static PyObject *__pyx_n_find;

/* "/opt/src/bpbio/seqfind/seqfind.pyx":34
 *     void Py_INCREF(object)
 * 
 * cdef inline size_t imin(int a, int b, int c):             # <<<<<<<<<<<<<< 
 *     if a < b:
 *         if c < a:
 */

static INLINE size_t __pyx_f_7seqfind_imin(int __pyx_v_a, int __pyx_v_b, int __pyx_v_c) {
  size_t __pyx_r;
  int __pyx_1;

  /* "/opt/src/bpbio/seqfind/seqfind.pyx":35
 * 
 * cdef inline size_t imin(int a, int b, int c):
 *     if a < b:             # <<<<<<<<<<<<<< 
 *         if c < a:
 *             return c
 */
  __pyx_1 = (__pyx_v_a < __pyx_v_b);
  if (__pyx_1) {

    /* "/opt/src/bpbio/seqfind/seqfind.pyx":36
 * cdef inline size_t imin(int a, int b, int c):
 *     if a < b:
 *         if c < a:             # <<<<<<<<<<<<<< 
 *             return c
 *         return a
 */
    __pyx_1 = (__pyx_v_c < __pyx_v_a);
    if (__pyx_1) {

      /* "/opt/src/bpbio/seqfind/seqfind.pyx":37
 *     if a < b:
 *         if c < a:
 *             return c             # <<<<<<<<<<<<<< 
 *         return a
 *     if c < b:
 */
      __pyx_r = __pyx_v_c;
      goto __pyx_L0;
      goto __pyx_L3;
    }
    __pyx_L3:;

    /* "/opt/src/bpbio/seqfind/seqfind.pyx":38
 *         if c < a:
 *             return c
 *         return a             # <<<<<<<<<<<<<< 
 *     if c < b:
 *         return c
 */
    __pyx_r = __pyx_v_a;
    goto __pyx_L0;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/opt/src/bpbio/seqfind/seqfind.pyx":39
 *             return c
 *         return a
 *     if c < b:             # <<<<<<<<<<<<<< 
 *         return c
 *     return b
 */
  __pyx_1 = (__pyx_v_c < __pyx_v_b);
  if (__pyx_1) {

    /* "/opt/src/bpbio/seqfind/seqfind.pyx":40
 *         return a
 *     if c < b:
 *         return c             # <<<<<<<<<<<<<< 
 *     return b
 * 
 */
    __pyx_r = __pyx_v_c;
    goto __pyx_L0;
    goto __pyx_L4;
  }
  __pyx_L4:;

  /* "/opt/src/bpbio/seqfind/seqfind.pyx":41
 *     if c < b:
 *         return c
 *     return b             # <<<<<<<<<<<<<< 
 * 
 * 
 */
  __pyx_r = __pyx_v_b;
  goto __pyx_L0;

  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

/* "/opt/src/bpbio/seqfind/seqfind.pyx":44
 * 
 * 
 * cpdef int edit_distance(char *a, char *b, int limit):             # <<<<<<<<<<<<<< 
 *     """
 *     the damerau-levenshtein distance:
 */

static PyObject *__pyx_pf_7seqfind_edit_distance(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static  int __pyx_f_7seqfind_edit_distance(char *__pyx_v_a, char *__pyx_v_b, int __pyx_v_limit) {
  int __pyx_v_alen;
  int __pyx_v_blen;
  int __pyx_v_retval;
  char *__pyx_v_ctmp;
  size_t __pyx_v_i;
  size_t __pyx_v_j;
  size_t __pyx_v_achr;
  size_t __pyx_v_bchr;
  char *__pyx_v_m1;
  char *__pyx_v_m2;
  char *__pyx_v_m3;
  int __pyx_r;
  int __pyx_1;
  int __pyx_2;
  int __pyx_3;
  char *__pyx_4;
  char *__pyx_5;

  /* "/opt/src/bpbio/seqfind/seqfind.pyx":68
 * 
 * 
 *     cdef int alen = strlen(a), blen = strlen(b), retval             # <<<<<<<<<<<<<< 
 *     cdef char *ctmp
 *     cdef size_t i, j
 */
  __pyx_v_alen = strlen(__pyx_v_a);

  __pyx_v_blen = strlen(__pyx_v_b);


  /* "/opt/src/bpbio/seqfind/seqfind.pyx":73
 *     cdef size_t achr, bchr
 *      
 *     if strcmp(a, b) == 0:             # <<<<<<<<<<<<<< 
 *         return 0
 * 
 */
  __pyx_1 = (strcmp(__pyx_v_a, __pyx_v_b) == 0);
  if (__pyx_1) {

    /* "/opt/src/bpbio/seqfind/seqfind.pyx":74
 *      
 *     if strcmp(a, b) == 0:
 *         return 0             # <<<<<<<<<<<<<< 
 * 
 *     if alen > blen:
 */
    __pyx_r = 0;
    goto __pyx_L0;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/opt/src/bpbio/seqfind/seqfind.pyx":76
 *         return 0
 * 
 *     if alen > blen:             # <<<<<<<<<<<<<< 
 *         ctmp = a;
 *         a = b;
 */
  __pyx_1 = (__pyx_v_alen > __pyx_v_blen);
  if (__pyx_1) {

    /* "/opt/src/bpbio/seqfind/seqfind.pyx":77
 * 
 *     if alen > blen:
 *         ctmp = a;             # <<<<<<<<<<<<<< 
 *         a = b;
 *         b = ctmp;
 */
    __pyx_v_ctmp = __pyx_v_a;

    /* "/opt/src/bpbio/seqfind/seqfind.pyx":78
 *     if alen > blen:
 *         ctmp = a;
 *         a = b;             # <<<<<<<<<<<<<< 
 *         b = ctmp;
 *         alen, blen = blen, alen
 */
    __pyx_v_a = __pyx_v_b;

    /* "/opt/src/bpbio/seqfind/seqfind.pyx":79
 *         ctmp = a;
 *         a = b;
 *         b = ctmp;             # <<<<<<<<<<<<<< 
 *         alen, blen = blen, alen
 *         
 */
    __pyx_v_b = __pyx_v_ctmp;

    /* "/opt/src/bpbio/seqfind/seqfind.pyx":80
 *         a = b;
 *         b = ctmp;
 *         alen, blen = blen, alen             # <<<<<<<<<<<<<< 
 *         
 *     # short circuit.
 */
    __pyx_2 = __pyx_v_blen;
    __pyx_3 = __pyx_v_alen;
    __pyx_v_alen = __pyx_2;
    __pyx_v_blen = __pyx_3;
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "/opt/src/bpbio/seqfind/seqfind.pyx":83
 *         
 *     # short circuit.
 *     if blen - alen >= limit:             # <<<<<<<<<<<<<< 
 *         return blen - alen
 * 
 */
  __pyx_1 = ((__pyx_v_blen - __pyx_v_alen) >= __pyx_v_limit);
  if (__pyx_1) {

    /* "/opt/src/bpbio/seqfind/seqfind.pyx":84
 *     # short circuit.
 *     if blen - alen >= limit:
 *         return blen - alen             # <<<<<<<<<<<<<< 
 * 
 *     cdef char *m1 = <char *>calloc(blen + 2, sizeof(char))
 */
    __pyx_r = (__pyx_v_blen - __pyx_v_alen);
    goto __pyx_L0;
    goto __pyx_L4;
  }
  __pyx_L4:;

  /* "/opt/src/bpbio/seqfind/seqfind.pyx":86
 *         return blen - alen
 * 
 *     cdef char *m1 = <char *>calloc(blen + 2, sizeof(char))             # <<<<<<<<<<<<<< 
 *     cdef char *m2 = <char *>calloc(blen + 2, sizeof(char))
 *     cdef char *m3 = <char *>malloc((blen + 2) * sizeof(char))
 */
  __pyx_v_m1 = ((char *)calloc((__pyx_v_blen + 2), (sizeof(char))));


  /* "/opt/src/bpbio/seqfind/seqfind.pyx":87
 * 
 *     cdef char *m1 = <char *>calloc(blen + 2, sizeof(char))
 *     cdef char *m2 = <char *>calloc(blen + 2, sizeof(char))             # <<<<<<<<<<<<<< 
 *     cdef char *m3 = <char *>malloc((blen + 2) * sizeof(char))
 *     
 */
  __pyx_v_m2 = ((char *)calloc((__pyx_v_blen + 2), (sizeof(char))));


  /* "/opt/src/bpbio/seqfind/seqfind.pyx":88
 *     cdef char *m1 = <char *>calloc(blen + 2, sizeof(char))
 *     cdef char *m2 = <char *>calloc(blen + 2, sizeof(char))
 *     cdef char *m3 = <char *>malloc((blen + 2) * sizeof(char))             # <<<<<<<<<<<<<< 
 *     
 *     for i from 0 <= i <= blen:
 */
  __pyx_v_m3 = ((char *)malloc(((__pyx_v_blen + 2) * (sizeof(char)))));


  /* "/opt/src/bpbio/seqfind/seqfind.pyx":90
 *     cdef char *m3 = <char *>malloc((blen + 2) * sizeof(char))
 *     
 *     for i from 0 <= i <= blen:             # <<<<<<<<<<<<<< 
 *         m2[i] = i 
 * 
 */
  for (__pyx_v_i = 0; __pyx_v_i <= __pyx_v_blen; __pyx_v_i++) {

    /* "/opt/src/bpbio/seqfind/seqfind.pyx":91
 *     
 *     for i from 0 <= i <= blen:
 *         m2[i] = i             # <<<<<<<<<<<<<< 
 * 
 *     for i from 1 <= i <= alen:
 */
    (__pyx_v_m2[__pyx_v_i]) = __pyx_v_i;
  }

  /* "/opt/src/bpbio/seqfind/seqfind.pyx":93
 *         m2[i] = i 
 * 
 *     for i from 1 <= i <= alen:             # <<<<<<<<<<<<<< 
 *         m1[0] = i + 1
 *         achr = a[i - 1]
 */
  for (__pyx_v_i = 1; __pyx_v_i <= __pyx_v_alen; __pyx_v_i++) {

    /* "/opt/src/bpbio/seqfind/seqfind.pyx":94
 * 
 *     for i from 1 <= i <= alen:
 *         m1[0] = i + 1             # <<<<<<<<<<<<<< 
 *         achr = a[i - 1]
 *         for j from 1 <= j <= blen:
 */
    (__pyx_v_m1[0]) = (__pyx_v_i + 1);

    /* "/opt/src/bpbio/seqfind/seqfind.pyx":95
 *     for i from 1 <= i <= alen:
 *         m1[0] = i + 1
 *         achr = a[i - 1]             # <<<<<<<<<<<<<< 
 *         for j from 1 <= j <= blen:
 *             bchr = b[j- 1]
 */
    __pyx_v_achr = (__pyx_v_a[(__pyx_v_i - 1)]);

    /* "/opt/src/bpbio/seqfind/seqfind.pyx":96
 *         m1[0] = i + 1
 *         achr = a[i - 1]
 *         for j from 1 <= j <= blen:             # <<<<<<<<<<<<<< 
 *             bchr = b[j- 1]
 *             if achr == bchr:
 */
    for (__pyx_v_j = 1; __pyx_v_j <= __pyx_v_blen; __pyx_v_j++) {

      /* "/opt/src/bpbio/seqfind/seqfind.pyx":97
 *         achr = a[i - 1]
 *         for j from 1 <= j <= blen:
 *             bchr = b[j- 1]             # <<<<<<<<<<<<<< 
 *             if achr == bchr:
 *                 m1[j] = m2[j - 1]
 */
      __pyx_v_bchr = (__pyx_v_b[(__pyx_v_j - 1)]);

      /* "/opt/src/bpbio/seqfind/seqfind.pyx":98
 *         for j from 1 <= j <= blen:
 *             bchr = b[j- 1]
 *             if achr == bchr:             # <<<<<<<<<<<<<< 
 *                 m1[j] = m2[j - 1]
 *             else:
 */
      __pyx_1 = (__pyx_v_achr == __pyx_v_bchr);
      if (__pyx_1) {

        /* "/opt/src/bpbio/seqfind/seqfind.pyx":99
 *             bchr = b[j- 1]
 *             if achr == bchr:
 *                 m1[j] = m2[j - 1]             # <<<<<<<<<<<<<< 
 *             else:
 *                 m1[j] = 1 + imin(m1[j - 1], m2[j - 1], m2[j])
 */
        (__pyx_v_m1[__pyx_v_j]) = (__pyx_v_m2[(__pyx_v_j - 1)]);
        goto __pyx_L11;
      }
      /*else*/ {

        /* "/opt/src/bpbio/seqfind/seqfind.pyx":101
 *                 m1[j] = m2[j - 1]
 *             else:
 *                 m1[j] = 1 + imin(m1[j - 1], m2[j - 1], m2[j])             # <<<<<<<<<<<<<< 
 * 
 *             if i != 1 and j != 1 and achr == b[j - 2] and bchr == a[i - 2]: # and m1[j] > m3[j - 1] + cost:
 */
        (__pyx_v_m1[__pyx_v_j]) = (1 + __pyx_f_7seqfind_imin((__pyx_v_m1[(__pyx_v_j - 1)]), (__pyx_v_m2[(__pyx_v_j - 1)]), (__pyx_v_m2[__pyx_v_j])));
      }
      __pyx_L11:;

      /* "/opt/src/bpbio/seqfind/seqfind.pyx":103
 *                 m1[j] = 1 + imin(m1[j - 1], m2[j - 1], m2[j])
 * 
 *             if i != 1 and j != 1 and achr == b[j - 2] and bchr == a[i - 2]: # and m1[j] > m3[j - 1] + cost:             # <<<<<<<<<<<<<< 
 *                     m1[j] = m3[j - 1] 
 * 
 */
      __pyx_1 = (__pyx_v_i != 1);
      if (__pyx_1) {
        __pyx_1 = (__pyx_v_j != 1);
        if (__pyx_1) {
          __pyx_1 = (__pyx_v_achr == (__pyx_v_b[(__pyx_v_j - 2)]));
          if (__pyx_1) {
            __pyx_1 = (__pyx_v_bchr == (__pyx_v_a[(__pyx_v_i - 2)]));
          }
        }
      }
      if (__pyx_1) {

        /* "/opt/src/bpbio/seqfind/seqfind.pyx":104
 * 
 *             if i != 1 and j != 1 and achr == b[j - 2] and bchr == a[i - 2]: # and m1[j] > m3[j - 1] + cost:
 *                     m1[j] = m3[j - 1]             # <<<<<<<<<<<<<< 
 * 
 *         m1, m2 = m2, m1
 */
        (__pyx_v_m1[__pyx_v_j]) = (__pyx_v_m3[(__pyx_v_j - 1)]);
        goto __pyx_L12;
      }
      __pyx_L12:;
    }

    /* "/opt/src/bpbio/seqfind/seqfind.pyx":106
 *                     m1[j] = m3[j - 1] 
 * 
 *         m1, m2 = m2, m1             # <<<<<<<<<<<<<< 
 *         strcpy(m3, m2)
 * 
 */
    __pyx_4 = __pyx_v_m2;
    __pyx_5 = __pyx_v_m1;
    __pyx_v_m1 = __pyx_4;
    __pyx_v_m2 = __pyx_5;

    /* "/opt/src/bpbio/seqfind/seqfind.pyx":107
 * 
 *         m1, m2 = m2, m1
 *         strcpy(m3, m2)             # <<<<<<<<<<<<<< 
 * 
 *     retval = <int>m2[blen]
 */
    strcpy(__pyx_v_m3, __pyx_v_m2);
  }

  /* "/opt/src/bpbio/seqfind/seqfind.pyx":109
 *         strcpy(m3, m2)
 * 
 *     retval = <int>m2[blen]             # <<<<<<<<<<<<<< 
 *     free(m3)
 *     free(m1)
 */
  __pyx_v_retval = ((int)(__pyx_v_m2[__pyx_v_blen]));

  /* "/opt/src/bpbio/seqfind/seqfind.pyx":110
 * 
 *     retval = <int>m2[blen]
 *     free(m3)             # <<<<<<<<<<<<<< 
 *     free(m1)
 *     free(m2)
 */
  free(__pyx_v_m3);

  /* "/opt/src/bpbio/seqfind/seqfind.pyx":111
 *     retval = <int>m2[blen]
 *     free(m3)
 *     free(m1)             # <<<<<<<<<<<<<< 
 *     free(m2)
 *     return retval
 */
  free(__pyx_v_m1);

  /* "/opt/src/bpbio/seqfind/seqfind.pyx":112
 *     free(m3)
 *     free(m1)
 *     free(m2)             # <<<<<<<<<<<<<< 
 *     return retval
 * 
 */
  free(__pyx_v_m2);

  /* "/opt/src/bpbio/seqfind/seqfind.pyx":113
 *     free(m1)
 *     free(m2)
 *     return retval             # <<<<<<<<<<<<<< 
 * 
 * 
 */
  __pyx_r = __pyx_v_retval;
  goto __pyx_L0;

  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

/* "/opt/src/bpbio/seqfind/seqfind.pyx":44
 * 
 * 
 * cpdef int edit_distance(char *a, char *b, int limit):             # <<<<<<<<<<<<<< 
 *     """
 *     the damerau-levenshtein distance:
 */

static PyObject *__pyx_pf_7seqfind_edit_distance(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_7seqfind_edit_distance[] = "\n    the damerau-levenshtein distance:\n    http://en.wikipedia.org/wiki/Damerau-Levenshtein_distance\n    which differs from levenshtein in having only 1 point for a\n    transposition:\n        \"zzabzz\" => \"zzbazz\" levenshtein == 2\n        \"zzabzz\" => \"zzbazz\" damerau-lev == 1\n\n    takes 2 strings and a limit, if the strings have a length\n    difference > limit\n\n    >>> edit_distance(\"asdf\", \"acdf\", 100)\n    1\n\n    >>> edit_distance(\"acdf\", \"acdf\", 100)\n    0\n\n    >>> edit_distance(\"ac\", \"ca\", 100)\n    1\n    ";
static PyObject *__pyx_pf_7seqfind_edit_distance(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  char *__pyx_v_a;
  char *__pyx_v_b;
  int __pyx_v_limit;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {"a","b","limit",0};
  if (likely(!__pyx_kwds) && likely(PyTuple_GET_SIZE(__pyx_args) == 3)) {
    __pyx_v_a = PyString_AsString(PyTuple_GET_ITEM(__pyx_args, 0)); if (unlikely((!__pyx_v_a) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; __pyx_clineno = __LINE__; goto __pyx_L2;}
    __pyx_v_b = PyString_AsString(PyTuple_GET_ITEM(__pyx_args, 1)); if (unlikely((!__pyx_v_b) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; __pyx_clineno = __LINE__; goto __pyx_L2;}
    __pyx_v_limit = __pyx_PyInt_int(PyTuple_GET_ITEM(__pyx_args, 2)); if (unlikely((__pyx_v_limit == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; __pyx_clineno = __LINE__; goto __pyx_L2;}
  }
  else {
    if (unlikely(!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "ssi", __pyx_argnames, &__pyx_v_a, &__pyx_v_b, &__pyx_v_limit))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; __pyx_clineno = __LINE__; goto __pyx_L2;}
  }
  goto __pyx_L3;
  __pyx_L2:;
  __Pyx_AddTraceback("seqfind.edit_distance");
  return NULL;
  __pyx_L3:;
  __pyx_1 = PyInt_FromLong(__pyx_f_7seqfind_edit_distance(__pyx_v_a, __pyx_v_b, __pyx_v_limit)); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("seqfind.edit_distance");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/opt/src/bpbio/seqfind/seqfind.pyx":121
 *     cdef public int distance
 * 
 *     def __cinit__(self, char * word, object info=None): #, char* info):             # <<<<<<<<<<<<<< 
 *         self.word = word
 *         self.info = info
 */

static int __pyx_pf_7seqfind_4Word___cinit__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_pf_7seqfind_4Word___cinit__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  char *__pyx_v_word;
  PyObject *__pyx_v_info = 0;
  int __pyx_r;
  static char *__pyx_argnames[] = {"word","info",0};
  __pyx_v_info = Py_None;
  if (likely(!__pyx_kwds) && likely(1 <= PyTuple_GET_SIZE(__pyx_args)) && likely(PyTuple_GET_SIZE(__pyx_args) <= 2)) {
    __pyx_v_word = PyString_AsString(PyTuple_GET_ITEM(__pyx_args, 0)); if (unlikely((!__pyx_v_word) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 121; __pyx_clineno = __LINE__; goto __pyx_L2;}
    if (PyTuple_GET_SIZE(__pyx_args) > 1) {
      __pyx_v_info = PyTuple_GET_ITEM(__pyx_args, 1);
    }
  }
  else {
    if (unlikely(!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "s|O", __pyx_argnames, &__pyx_v_word, &__pyx_v_info))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 121; __pyx_clineno = __LINE__; goto __pyx_L2;}
  }
  goto __pyx_L3;
  __pyx_L2:;
  __Pyx_AddTraceback("seqfind.Word.__cinit__");
  return -1;
  __pyx_L3:;

  /* "/opt/src/bpbio/seqfind/seqfind.pyx":122
 * 
 *     def __cinit__(self, char * word, object info=None): #, char* info):
 *         self.word = word             # <<<<<<<<<<<<<< 
 *         self.info = info
 * 
 */
  ((struct __pyx_obj_7seqfind_Word *)__pyx_v_self)->word = __pyx_v_word;

  /* "/opt/src/bpbio/seqfind/seqfind.pyx":123
 *     def __cinit__(self, char * word, object info=None): #, char* info):
 *         self.word = word
 *         self.info = info             # <<<<<<<<<<<<<< 
 * 
 *     def __repr__(self):
 */
  Py_INCREF(__pyx_v_info);
  Py_DECREF(((struct __pyx_obj_7seqfind_Word *)__pyx_v_self)->info);
  ((struct __pyx_obj_7seqfind_Word *)__pyx_v_self)->info = __pyx_v_info;

  __pyx_r = 0;
  return __pyx_r;
}

/* "/opt/src/bpbio/seqfind/seqfind.pyx":125
 *         self.info = info
 * 
 *     def __repr__(self):             # <<<<<<<<<<<<<< 
 *         return "<Word. {'word': '%s' }>" % self.word
 * 
 */

static PyObject *__pyx_k_1p;

static char __pyx_k_1[] = "<Word. {'word': '%s' }>";

static PyObject *__pyx_pf_7seqfind_4Word___repr__(PyObject *__pyx_v_self); /*proto*/
static PyObject *__pyx_pf_7seqfind_4Word___repr__(PyObject *__pyx_v_self) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;

  /* "/opt/src/bpbio/seqfind/seqfind.pyx":126
 * 
 *     def __repr__(self):
 *         return "<Word. {'word': '%s' }>" % self.word             # <<<<<<<<<<<<<< 
 * 
 * cdef class BKTree:
 */
  __pyx_1 = PyString_FromString(((struct __pyx_obj_7seqfind_Word *)__pyx_v_self)->word); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 126; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = PyNumber_Remainder(__pyx_k_1p, __pyx_1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 126; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("seqfind.Word.__repr__");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/opt/src/bpbio/seqfind/seqfind.pyx":166
 *     cdef public object nodes
 * 
 *     def __init__(self, words):             # <<<<<<<<<<<<<< 
 *         cdef int is_word = 0
 *         cdef Word root 
 */

static int __pyx_pf_7seqfind_6BKTree___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_pf_7seqfind_6BKTree___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_words = 0;
  int __pyx_v_is_word;
  struct __pyx_obj_7seqfind_Word *__pyx_v_root;
  struct __pyx_obj_7seqfind_Word *__pyx_v_aword;
  PyObject *__pyx_v_w;
  int __pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  int __pyx_3;
  Py_ssize_t __pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  static char *__pyx_argnames[] = {"words",0};
  if (likely(!__pyx_kwds) && likely(PyTuple_GET_SIZE(__pyx_args) == 1)) {
    __pyx_v_words = PyTuple_GET_ITEM(__pyx_args, 0);
  }
  else {
    if (unlikely(!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_words))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 166; __pyx_clineno = __LINE__; goto __pyx_L2;}
  }
  goto __pyx_L3;
  __pyx_L2:;
  __Pyx_AddTraceback("seqfind.BKTree.__init__");
  return -1;
  __pyx_L3:;
  __pyx_v_root = ((struct __pyx_obj_7seqfind_Word *)Py_None); Py_INCREF(Py_None);
  __pyx_v_aword = ((struct __pyx_obj_7seqfind_Word *)Py_None); Py_INCREF(Py_None);
  __pyx_v_w = Py_None; Py_INCREF(Py_None);

  /* "/opt/src/bpbio/seqfind/seqfind.pyx":167
 * 
 *     def __init__(self, words):
 *         cdef int is_word = 0             # <<<<<<<<<<<<<< 
 *         cdef Word root 
 * 
 */
  __pyx_v_is_word = 0;


  /* "/opt/src/bpbio/seqfind/seqfind.pyx":170
 *         cdef Word root 
 * 
 *         if isinstance(words[0], Word):             # <<<<<<<<<<<<<< 
 *             is_word = 1
 *             root = words[0]
 */
  if (PyList_CheckExact(__pyx_v_words) && 0 <= 0 && 0 < PyList_GET_SIZE(__pyx_v_words)) {
    __pyx_2 = PyList_GET_ITEM(__pyx_v_words, 0); Py_INCREF(__pyx_2);
    } else if (PyTuple_CheckExact(__pyx_v_words) && 0 <= 0 && 0 < PyTuple_GET_SIZE(__pyx_v_words)) {
    __pyx_2 = PyTuple_GET_ITEM(__pyx_v_words, 0); Py_INCREF(__pyx_2);
    } else {
    __pyx_1 = PyInt_FromLong(0); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 170; __pyx_clineno = __LINE__; goto __pyx_L1;}
    __pyx_2 = PyObject_GetItem(__pyx_v_words, __pyx_1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 170; __pyx_clineno = __LINE__; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
  }
  __pyx_3 = PyObject_IsInstance(__pyx_2, ((PyObject*)__pyx_ptype_7seqfind_Word)); if (unlikely(__pyx_3 == -1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 170; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (__pyx_3) {

    /* "/opt/src/bpbio/seqfind/seqfind.pyx":171
 * 
 *         if isinstance(words[0], Word):
 *             is_word = 1             # <<<<<<<<<<<<<< 
 *             root = words[0]
 *         else:
 */
    __pyx_v_is_word = 1;

    /* "/opt/src/bpbio/seqfind/seqfind.pyx":172
 *         if isinstance(words[0], Word):
 *             is_word = 1
 *             root = words[0]             # <<<<<<<<<<<<<< 
 *         else:
 *             root = Word(words[0])
 */
    if (PyList_CheckExact(__pyx_v_words) && 0 <= 0 && 0 < PyList_GET_SIZE(__pyx_v_words)) {
      __pyx_2 = PyList_GET_ITEM(__pyx_v_words, 0); Py_INCREF(__pyx_2);
      } else if (PyTuple_CheckExact(__pyx_v_words) && 0 <= 0 && 0 < PyTuple_GET_SIZE(__pyx_v_words)) {
      __pyx_2 = PyTuple_GET_ITEM(__pyx_v_words, 0); Py_INCREF(__pyx_2);
      } else {
      __pyx_1 = PyInt_FromLong(0); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 172; __pyx_clineno = __LINE__; goto __pyx_L1;}
      __pyx_2 = PyObject_GetItem(__pyx_v_words, __pyx_1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 172; __pyx_clineno = __LINE__; goto __pyx_L1;}
      Py_DECREF(__pyx_1); __pyx_1 = 0;
    }
    if (!(__Pyx_TypeTest(__pyx_2, __pyx_ptype_7seqfind_Word))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 172; __pyx_clineno = __LINE__; goto __pyx_L1;}
    Py_DECREF(((PyObject *)__pyx_v_root));
    __pyx_v_root = ((struct __pyx_obj_7seqfind_Word *)__pyx_2);
    __pyx_2 = 0;
    goto __pyx_L4;
  }
  /*else*/ {

    /* "/opt/src/bpbio/seqfind/seqfind.pyx":174
 *             root = words[0]
 *         else:
 *             root = Word(words[0])             # <<<<<<<<<<<<<< 
 *         
 * 
 */
    if (PyList_CheckExact(__pyx_v_words) && 0 <= 0 && 0 < PyList_GET_SIZE(__pyx_v_words)) {
      __pyx_2 = PyList_GET_ITEM(__pyx_v_words, 0); Py_INCREF(__pyx_2);
      } else if (PyTuple_CheckExact(__pyx_v_words) && 0 <= 0 && 0 < PyTuple_GET_SIZE(__pyx_v_words)) {
      __pyx_2 = PyTuple_GET_ITEM(__pyx_v_words, 0); Py_INCREF(__pyx_2);
      } else {
      __pyx_1 = PyInt_FromLong(0); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 174; __pyx_clineno = __LINE__; goto __pyx_L1;}
      __pyx_2 = PyObject_GetItem(__pyx_v_words, __pyx_1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 174; __pyx_clineno = __LINE__; goto __pyx_L1;}
      Py_DECREF(__pyx_1); __pyx_1 = 0;
    }
    __pyx_1 = PyTuple_New(1); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 174; __pyx_clineno = __LINE__; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_1, 0, __pyx_2);
    __pyx_2 = 0;
    __pyx_2 = PyObject_Call(((PyObject*)__pyx_ptype_7seqfind_Word), ((PyObject *)__pyx_1), NULL); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 174; __pyx_clineno = __LINE__; goto __pyx_L1;}
    Py_DECREF(((PyObject *)__pyx_1)); __pyx_1 = 0;
    if (!(__Pyx_TypeTest(__pyx_2, __pyx_ptype_7seqfind_Word))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 174; __pyx_clineno = __LINE__; goto __pyx_L1;}
    Py_DECREF(((PyObject *)__pyx_v_root));
    __pyx_v_root = ((struct __pyx_obj_7seqfind_Word *)__pyx_2);
    __pyx_2 = 0;
  }
  __pyx_L4:;

  /* "/opt/src/bpbio/seqfind/seqfind.pyx":178
 * 
 *         cdef Word aword
 *         self.root = root             # <<<<<<<<<<<<<< 
 *         self.nodes = {root: []}
 *         for w in words[1:]:
 */
  Py_INCREF(((PyObject *)__pyx_v_root));
  Py_DECREF(((PyObject *)((struct __pyx_obj_7seqfind_BKTree *)__pyx_v_self)->root));
  ((struct __pyx_obj_7seqfind_BKTree *)__pyx_v_self)->root = __pyx_v_root;

  /* "/opt/src/bpbio/seqfind/seqfind.pyx":179
 *         cdef Word aword
 *         self.root = root
 *         self.nodes = {root: []}             # <<<<<<<<<<<<<< 
 *         for w in words[1:]:
 *             if is_word == 0:
 */
  __pyx_1 = PyDict_New(); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 179; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = PyList_New(0); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 179; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_1, ((PyObject *)__pyx_v_root), ((PyObject *)__pyx_2)) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 179; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_2)); __pyx_2 = 0;
  Py_DECREF(((struct __pyx_obj_7seqfind_BKTree *)__pyx_v_self)->nodes);
  ((struct __pyx_obj_7seqfind_BKTree *)__pyx_v_self)->nodes = ((PyObject *)__pyx_1);
  __pyx_1 = 0;

  /* "/opt/src/bpbio/seqfind/seqfind.pyx":180
 *         self.root = root
 *         self.nodes = {root: []}
 *         for w in words[1:]:             # <<<<<<<<<<<<<< 
 *             if is_word == 0:
 *                 aword = Word(w)
 */
  __pyx_2 = PySequence_GetSlice(__pyx_v_words, 1, PY_SSIZE_T_MAX); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 180; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (PyList_CheckExact(__pyx_2)) { __pyx_4 = 0; __pyx_1 = __pyx_2; Py_INCREF(__pyx_1); }
  else { __pyx_1 = PyObject_GetIter(__pyx_2); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 180; __pyx_clineno = __LINE__; goto __pyx_L1;} }
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  for (;;) {
    if (PyList_CheckExact(__pyx_1)) { if (__pyx_4 >= PyList_GET_SIZE(__pyx_1)) break; __pyx_2 = PyList_GET_ITEM(__pyx_1, __pyx_4++); Py_INCREF(__pyx_2); }
    else {
      __pyx_2 = PyIter_Next(__pyx_1);
      if (!__pyx_2) {
        break;
      }
    }
    Py_DECREF(__pyx_v_w);
    __pyx_v_w = __pyx_2;
    __pyx_2 = 0;

    /* "/opt/src/bpbio/seqfind/seqfind.pyx":181
 *         self.nodes = {root: []}
 *         for w in words[1:]:
 *             if is_word == 0:             # <<<<<<<<<<<<<< 
 *                 aword = Word(w)
 *             else: 
 */
    __pyx_3 = (__pyx_v_is_word == 0);
    if (__pyx_3) {

      /* "/opt/src/bpbio/seqfind/seqfind.pyx":182
 *         for w in words[1:]:
 *             if is_word == 0:
 *                 aword = Word(w)             # <<<<<<<<<<<<<< 
 *             else: 
 *                 aword = w
 */
      __pyx_2 = PyTuple_New(1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 182; __pyx_clineno = __LINE__; goto __pyx_L1;}
      Py_INCREF(__pyx_v_w);
      PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_w);
      __pyx_5 = PyObject_Call(((PyObject*)__pyx_ptype_7seqfind_Word), ((PyObject *)__pyx_2), NULL); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 182; __pyx_clineno = __LINE__; goto __pyx_L1;}
      Py_DECREF(((PyObject *)__pyx_2)); __pyx_2 = 0;
      if (!(__Pyx_TypeTest(__pyx_5, __pyx_ptype_7seqfind_Word))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 182; __pyx_clineno = __LINE__; goto __pyx_L1;}
      Py_DECREF(((PyObject *)__pyx_v_aword));
      __pyx_v_aword = ((struct __pyx_obj_7seqfind_Word *)__pyx_5);
      __pyx_5 = 0;
      goto __pyx_L7;
    }
    /*else*/ {

      /* "/opt/src/bpbio/seqfind/seqfind.pyx":184
 *                 aword = Word(w)
 *             else: 
 *                 aword = w             # <<<<<<<<<<<<<< 
 *             if aword in self.nodes: continue
 *             self.addNode(root, aword)
 */
      if (!(__Pyx_TypeTest(__pyx_v_w, __pyx_ptype_7seqfind_Word))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 184; __pyx_clineno = __LINE__; goto __pyx_L1;}
      Py_INCREF(__pyx_v_w);
      Py_DECREF(((PyObject *)__pyx_v_aword));
      __pyx_v_aword = ((struct __pyx_obj_7seqfind_Word *)__pyx_v_w);
    }
    __pyx_L7:;

    /* "/opt/src/bpbio/seqfind/seqfind.pyx":185
 *             else: 
 *                 aword = w
 *             if aword in self.nodes: continue             # <<<<<<<<<<<<<< 
 *             self.addNode(root, aword)
 * 
 */
    __pyx_3 = (PySequence_Contains(((struct __pyx_obj_7seqfind_BKTree *)__pyx_v_self)->nodes, ((PyObject *)__pyx_v_aword))); if (unlikely(__pyx_3 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 185; __pyx_clineno = __LINE__; goto __pyx_L1;}
    if (__pyx_3) {
      goto __pyx_L5;
      goto __pyx_L8;
    }
    __pyx_L8:;

    /* "/opt/src/bpbio/seqfind/seqfind.pyx":186
 *                 aword = w
 *             if aword in self.nodes: continue
 *             self.addNode(root, aword)             # <<<<<<<<<<<<<< 
 * 
 *     cdef addNode(self, Word root, Word word):
 */
    __pyx_2 = ((struct __pyx_vtabstruct_7seqfind_BKTree *)((struct __pyx_obj_7seqfind_BKTree *)__pyx_v_self)->__pyx_vtab)->addNode(((struct __pyx_obj_7seqfind_BKTree *)__pyx_v_self), __pyx_v_root, __pyx_v_aword); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 186; __pyx_clineno = __LINE__; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_L5:;
  }
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("seqfind.BKTree.__init__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_root);
  Py_DECREF(__pyx_v_aword);
  Py_DECREF(__pyx_v_w);
  return __pyx_r;
}

/* "/opt/src/bpbio/seqfind/seqfind.pyx":188
 *             self.addNode(root, aword)
 * 
 *     cdef addNode(self, Word root, Word word):             # <<<<<<<<<<<<<< 
 *         cdef int d = edit_distance(root.word, word.word, 1000)
 * 
 */

static PyObject *__pyx_n_append;

static  PyObject *__pyx_f_7seqfind_6BKTree_addNode(struct __pyx_obj_7seqfind_BKTree *__pyx_v_self, struct __pyx_obj_7seqfind_Word *__pyx_v_root, struct __pyx_obj_7seqfind_Word *__pyx_v_word) {
  int __pyx_v_d;
  struct __pyx_obj_7seqfind_Word *__pyx_v_arc;
  PyObject *__pyx_r;
  int __pyx_1;
  Py_ssize_t __pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  int __pyx_5;
  PyObject *__pyx_6 = 0;
  __pyx_v_arc = ((struct __pyx_obj_7seqfind_Word *)Py_None); Py_INCREF(Py_None);

  /* "/opt/src/bpbio/seqfind/seqfind.pyx":189
 * 
 *     cdef addNode(self, Word root, Word word):
 *         cdef int d = edit_distance(root.word, word.word, 1000)             # <<<<<<<<<<<<<< 
 * 
 *         if d == 0: return None
 */
  __pyx_v_d = __pyx_f_7seqfind_edit_distance(__pyx_v_root->word, __pyx_v_word->word, 1000);


  /* "/opt/src/bpbio/seqfind/seqfind.pyx":191
 *         cdef int d = edit_distance(root.word, word.word, 1000)
 * 
 *         if d == 0: return None             # <<<<<<<<<<<<<< 
 * 
 *         cdef Word arc
 */
  __pyx_1 = (__pyx_v_d == 0);
  if (__pyx_1) {
    Py_INCREF(Py_None);
    __pyx_r = Py_None;
    goto __pyx_L0;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/opt/src/bpbio/seqfind/seqfind.pyx":194
 * 
 *         cdef Word arc
 *         for arc in self.nodes[root]:             # <<<<<<<<<<<<<< 
 *             if d != arc.distance: continue
 *             self.addNode(arc, word)
 */
  __pyx_3 = PyObject_GetItem(__pyx_v_self->nodes, ((PyObject *)__pyx_v_root)); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 194; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (PyList_CheckExact(__pyx_3)) { __pyx_2 = 0; __pyx_4 = __pyx_3; Py_INCREF(__pyx_4); }
  else { __pyx_4 = PyObject_GetIter(__pyx_3); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 194; __pyx_clineno = __LINE__; goto __pyx_L1;} }
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  for (;;) {
    if (PyList_CheckExact(__pyx_4)) { if (__pyx_2 >= PyList_GET_SIZE(__pyx_4)) break; __pyx_3 = PyList_GET_ITEM(__pyx_4, __pyx_2++); Py_INCREF(__pyx_3); }
    else {
      __pyx_3 = PyIter_Next(__pyx_4);
      if (!__pyx_3) {
        break;
      }
    }
    if (!(__Pyx_TypeTest(__pyx_3, __pyx_ptype_7seqfind_Word))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 194; __pyx_clineno = __LINE__; goto __pyx_L1;}
    Py_DECREF(((PyObject *)__pyx_v_arc));
    __pyx_v_arc = ((struct __pyx_obj_7seqfind_Word *)__pyx_3);
    __pyx_3 = 0;

    /* "/opt/src/bpbio/seqfind/seqfind.pyx":195
 *         cdef Word arc
 *         for arc in self.nodes[root]:
 *             if d != arc.distance: continue             # <<<<<<<<<<<<<< 
 *             self.addNode(arc, word)
 *             break
 */
    __pyx_1 = (__pyx_v_d != __pyx_v_arc->distance);
    if (__pyx_1) {
      goto __pyx_L3;
      goto __pyx_L5;
    }
    __pyx_L5:;

    /* "/opt/src/bpbio/seqfind/seqfind.pyx":196
 *         for arc in self.nodes[root]:
 *             if d != arc.distance: continue
 *             self.addNode(arc, word)             # <<<<<<<<<<<<<< 
 *             break
 * 
 */
    __pyx_3 = ((struct __pyx_vtabstruct_7seqfind_BKTree *)__pyx_v_self->__pyx_vtab)->addNode(__pyx_v_self, __pyx_v_arc, __pyx_v_word); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 196; __pyx_clineno = __LINE__; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;

    /* "/opt/src/bpbio/seqfind/seqfind.pyx":197
 *             if d != arc.distance: continue
 *             self.addNode(arc, word)
 *             break             # <<<<<<<<<<<<<< 
 * 
 *         else:
 */
    goto __pyx_L4;
    __pyx_L3:;
  }
  /*else*/ {

    /* "/opt/src/bpbio/seqfind/seqfind.pyx":200
 * 
 *         else:
 *             if not word in self.nodes:             # <<<<<<<<<<<<<< 
 *                 self.nodes[word] = []
 *             word.distance = d
 */
    __pyx_1 = (PySequence_Contains(__pyx_v_self->nodes, ((PyObject *)__pyx_v_word))); if (unlikely(__pyx_1 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 200; __pyx_clineno = __LINE__; goto __pyx_L1;}
    __pyx_5 = (!__pyx_1);
    if (__pyx_5) {

      /* "/opt/src/bpbio/seqfind/seqfind.pyx":201
 *         else:
 *             if not word in self.nodes:
 *                 self.nodes[word] = []             # <<<<<<<<<<<<<< 
 *             word.distance = d
 *             self.nodes[root].append(word)
 */
      __pyx_3 = PyList_New(0); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 201; __pyx_clineno = __LINE__; goto __pyx_L1;}
      if (PyObject_SetItem(__pyx_v_self->nodes, ((PyObject *)__pyx_v_word), ((PyObject *)__pyx_3)) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 201; __pyx_clineno = __LINE__; goto __pyx_L1;}
      Py_DECREF(((PyObject *)__pyx_3)); __pyx_3 = 0;
      goto __pyx_L6;
    }
    __pyx_L6:;

    /* "/opt/src/bpbio/seqfind/seqfind.pyx":202
 *             if not word in self.nodes:
 *                 self.nodes[word] = []
 *             word.distance = d             # <<<<<<<<<<<<<< 
 *             self.nodes[root].append(word)
 * 
 */
    __pyx_v_word->distance = __pyx_v_d;

    /* "/opt/src/bpbio/seqfind/seqfind.pyx":203
 *                 self.nodes[word] = []
 *             word.distance = d
 *             self.nodes[root].append(word)             # <<<<<<<<<<<<<< 
 * 
 * 
 */
    __pyx_3 = PyObject_GetItem(__pyx_v_self->nodes, ((PyObject *)__pyx_v_root)); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 203; __pyx_clineno = __LINE__; goto __pyx_L1;}
    __pyx_6 = __Pyx_PyObject_Append(__pyx_3, ((PyObject *)__pyx_v_word)); if (unlikely(!__pyx_6)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 203; __pyx_clineno = __LINE__; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_6); __pyx_6 = 0;
  }
  __pyx_L4:;
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_6);
  __Pyx_AddTraceback("seqfind.BKTree.addNode");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_arc);
  return __pyx_r;
}

/* "/opt/src/bpbio/seqfind/seqfind.pyx":206
 * 
 * 
 *     cpdef find(self, char *word, int thresh):             # <<<<<<<<<<<<<< 
 *         results = []
 *         self._find(self.root, Word(word), thresh, results)
 */

static PyObject *__pyx_pf_7seqfind_6BKTree_find(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static  PyObject *__pyx_f_7seqfind_6BKTree_find(struct __pyx_obj_7seqfind_BKTree *__pyx_v_self, char *__pyx_v_word, int __pyx_v_thresh) {
  PyObject *__pyx_v_results;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  __pyx_v_results = Py_None; Py_INCREF(Py_None);
  /* Check if called by wrapper */
  if (unlikely(__pyx_skip_dispatch)) __pyx_skip_dispatch = 0;
  /* Check if overriden in Python */
  else if (unlikely(((PyObject *)__pyx_v_self)->ob_type->tp_dictoffset != 0)) {
    __pyx_1 = PyObject_GetAttr(((PyObject *)__pyx_v_self), __pyx_n_find); if (unlikely(!((PyObject *)__pyx_v_self))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 206; __pyx_clineno = __LINE__; goto __pyx_L1;}
    if (!(strcmp(__pyx_1->ob_type->tp_name, "builtin_function_or_method") == 0) || (PyCFunction_GET_FUNCTION(__pyx_1) != (void *)&__pyx_pf_7seqfind_6BKTree_find)) {
      __pyx_2 = PyString_FromString(__pyx_v_word); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 206; __pyx_clineno = __LINE__; goto __pyx_L1;}
      __pyx_3 = PyInt_FromLong(__pyx_v_thresh); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 206; __pyx_clineno = __LINE__; goto __pyx_L1;}
      __pyx_4 = PyTuple_New(2); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 206; __pyx_clineno = __LINE__; goto __pyx_L1;}
      PyTuple_SET_ITEM(__pyx_4, 0, __pyx_2);
      PyTuple_SET_ITEM(__pyx_4, 1, __pyx_3);
      __pyx_2 = 0;
      __pyx_3 = 0;
      __pyx_2 = PyObject_Call(__pyx_1, ((PyObject *)__pyx_4), NULL); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 206; __pyx_clineno = __LINE__; goto __pyx_L1;}
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      Py_DECREF(((PyObject *)__pyx_4)); __pyx_4 = 0;
      __pyx_r = __pyx_2;
      __pyx_2 = 0;
      goto __pyx_L0;
    }
  }

  /* "/opt/src/bpbio/seqfind/seqfind.pyx":207
 * 
 *     cpdef find(self, char *word, int thresh):
 *         results = []             # <<<<<<<<<<<<<< 
 *         self._find(self.root, Word(word), thresh, results)
 *         return results
 */
  __pyx_3 = PyList_New(0); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 207; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_v_results);
  __pyx_v_results = ((PyObject *)__pyx_3);
  __pyx_3 = 0;

  /* "/opt/src/bpbio/seqfind/seqfind.pyx":208
 *     cpdef find(self, char *word, int thresh):
 *         results = []
 *         self._find(self.root, Word(word), thresh, results)             # <<<<<<<<<<<<<< 
 *         return results
 * 
 */
  __pyx_1 = PyString_FromString(__pyx_v_word); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 208; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(1); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 208; __pyx_clineno = __LINE__; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_1);
  __pyx_1 = 0;
  __pyx_2 = PyObject_Call(((PyObject*)__pyx_ptype_7seqfind_Word), ((PyObject *)__pyx_4), NULL); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 208; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_4)); __pyx_4 = 0;
  if (!(__Pyx_TypeTest(__pyx_2, __pyx_ptype_7seqfind_Word))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 208; __pyx_clineno = __LINE__; goto __pyx_L1;}
  ((struct __pyx_vtabstruct_7seqfind_BKTree *)__pyx_v_self->__pyx_vtab)->_find(__pyx_v_self, __pyx_v_self->root, ((struct __pyx_obj_7seqfind_Word *)__pyx_2), __pyx_v_thresh, __pyx_v_results);
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/opt/src/bpbio/seqfind/seqfind.pyx":209
 *         results = []
 *         self._find(self.root, Word(word), thresh, results)
 *         return results             # <<<<<<<<<<<<<< 
 * 
 *     cdef void _find(self, Word aroot, Word word, int thresh, results):
 */
  Py_INCREF(__pyx_v_results);
  __pyx_r = __pyx_v_results;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("seqfind.BKTree.find");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_results);
  return __pyx_r;
}

/* "/opt/src/bpbio/seqfind/seqfind.pyx":206
 * 
 * 
 *     cpdef find(self, char *word, int thresh):             # <<<<<<<<<<<<<< 
 *         results = []
 *         self._find(self.root, Word(word), thresh, results)
 */

static PyObject *__pyx_pf_7seqfind_6BKTree_find(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_pf_7seqfind_6BKTree_find(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  char *__pyx_v_word;
  int __pyx_v_thresh;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {"word","thresh",0};
  if (likely(!__pyx_kwds) && likely(PyTuple_GET_SIZE(__pyx_args) == 2)) {
    __pyx_v_word = PyString_AsString(PyTuple_GET_ITEM(__pyx_args, 0)); if (unlikely((!__pyx_v_word) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 206; __pyx_clineno = __LINE__; goto __pyx_L2;}
    __pyx_v_thresh = __pyx_PyInt_int(PyTuple_GET_ITEM(__pyx_args, 1)); if (unlikely((__pyx_v_thresh == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 206; __pyx_clineno = __LINE__; goto __pyx_L2;}
  }
  else {
    if (unlikely(!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "si", __pyx_argnames, &__pyx_v_word, &__pyx_v_thresh))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 206; __pyx_clineno = __LINE__; goto __pyx_L2;}
  }
  goto __pyx_L3;
  __pyx_L2:;
  __Pyx_AddTraceback("seqfind.BKTree.find");
  return NULL;
  __pyx_L3:;
  __pyx_1 = (__pyx_skip_dispatch = 1, ((struct __pyx_vtabstruct_7seqfind_BKTree *)((struct __pyx_obj_7seqfind_BKTree *)__pyx_v_self)->__pyx_vtab)->find(((struct __pyx_obj_7seqfind_BKTree *)__pyx_v_self), __pyx_v_word, __pyx_v_thresh)); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 206; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("seqfind.BKTree.find");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/opt/src/bpbio/seqfind/seqfind.pyx":211
 *         return results
 * 
 *     cdef void _find(self, Word aroot, Word word, int thresh, results):             # <<<<<<<<<<<<<< 
 *         cdef int arc_dist, d = edit_distance(word.word, aroot.word, 1000)
 *         cdef int dmin = d - thresh
 */

static  void __pyx_f_7seqfind_6BKTree__find(struct __pyx_obj_7seqfind_BKTree *__pyx_v_self, struct __pyx_obj_7seqfind_Word *__pyx_v_aroot, struct __pyx_obj_7seqfind_Word *__pyx_v_word, int __pyx_v_thresh, PyObject *__pyx_v_results) {
  int __pyx_v_arc_dist;
  int __pyx_v_d;
  int __pyx_v_dmin;
  int __pyx_v_dmax;
  struct __pyx_obj_7seqfind_Word *__pyx_v_arc;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  Py_ssize_t __pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  __pyx_v_arc = ((struct __pyx_obj_7seqfind_Word *)Py_None); Py_INCREF(Py_None);

  /* "/opt/src/bpbio/seqfind/seqfind.pyx":212
 * 
 *     cdef void _find(self, Word aroot, Word word, int thresh, results):
 *         cdef int arc_dist, d = edit_distance(word.word, aroot.word, 1000)             # <<<<<<<<<<<<<< 
 *         cdef int dmin = d - thresh
 *         cdef int dmax = d + thresh
 */
  __pyx_v_d = __pyx_f_7seqfind_edit_distance(__pyx_v_word->word, __pyx_v_aroot->word, 1000);


  /* "/opt/src/bpbio/seqfind/seqfind.pyx":213
 *     cdef void _find(self, Word aroot, Word word, int thresh, results):
 *         cdef int arc_dist, d = edit_distance(word.word, aroot.word, 1000)
 *         cdef int dmin = d - thresh             # <<<<<<<<<<<<<< 
 *         cdef int dmax = d + thresh
 *         cdef Word arc
 */
  __pyx_v_dmin = (__pyx_v_d - __pyx_v_thresh);


  /* "/opt/src/bpbio/seqfind/seqfind.pyx":214
 *         cdef int arc_dist, d = edit_distance(word.word, aroot.word, 1000)
 *         cdef int dmin = d - thresh
 *         cdef int dmax = d + thresh             # <<<<<<<<<<<<<< 
 *         cdef Word arc
 * 
 */
  __pyx_v_dmax = (__pyx_v_d + __pyx_v_thresh);


  /* "/opt/src/bpbio/seqfind/seqfind.pyx":217
 *         cdef Word arc
 * 
 *         if d <= thresh:             # <<<<<<<<<<<<<< 
 *             results.append(aroot)
 * 
 */
  __pyx_1 = (__pyx_v_d <= __pyx_v_thresh);
  if (__pyx_1) {

    /* "/opt/src/bpbio/seqfind/seqfind.pyx":218
 * 
 *         if d <= thresh:
 *             results.append(aroot)             # <<<<<<<<<<<<<< 
 * 
 *         # todo PyList_GetItem...
 */
    __pyx_2 = __Pyx_PyObject_Append(__pyx_v_results, ((PyObject *)__pyx_v_aroot)); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 218; __pyx_clineno = __LINE__; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/opt/src/bpbio/seqfind/seqfind.pyx":221
 * 
 *         # todo PyList_GetItem...
 *         for arc in self.nodes[aroot]:             # <<<<<<<<<<<<<< 
 *             arc_dist = arc.distance
 *             if dmin <= arc_dist <= dmax:
 */
  __pyx_2 = PyObject_GetItem(__pyx_v_self->nodes, ((PyObject *)__pyx_v_aroot)); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 221; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (PyList_CheckExact(__pyx_2)) { __pyx_3 = 0; __pyx_4 = __pyx_2; Py_INCREF(__pyx_4); }
  else { __pyx_4 = PyObject_GetIter(__pyx_2); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 221; __pyx_clineno = __LINE__; goto __pyx_L1;} }
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  for (;;) {
    if (PyList_CheckExact(__pyx_4)) { if (__pyx_3 >= PyList_GET_SIZE(__pyx_4)) break; __pyx_2 = PyList_GET_ITEM(__pyx_4, __pyx_3++); Py_INCREF(__pyx_2); }
    else {
      __pyx_2 = PyIter_Next(__pyx_4);
      if (!__pyx_2) {
        break;
      }
    }
    if (!(__Pyx_TypeTest(__pyx_2, __pyx_ptype_7seqfind_Word))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 221; __pyx_clineno = __LINE__; goto __pyx_L1;}
    Py_DECREF(((PyObject *)__pyx_v_arc));
    __pyx_v_arc = ((struct __pyx_obj_7seqfind_Word *)__pyx_2);
    __pyx_2 = 0;

    /* "/opt/src/bpbio/seqfind/seqfind.pyx":222
 *         # todo PyList_GetItem...
 *         for arc in self.nodes[aroot]:
 *             arc_dist = arc.distance             # <<<<<<<<<<<<<< 
 *             if dmin <= arc_dist <= dmax:
 *                 self._find(arc, word, thresh, results)
 */
    __pyx_v_arc_dist = __pyx_v_arc->distance;

    /* "/opt/src/bpbio/seqfind/seqfind.pyx":223
 *         for arc in self.nodes[aroot]:
 *             arc_dist = arc.distance
 *             if dmin <= arc_dist <= dmax:             # <<<<<<<<<<<<<< 
 *                 self._find(arc, word, thresh, results)
 * 
 */
    __pyx_1 = (__pyx_v_dmin <= __pyx_v_arc_dist);
    if (__pyx_1) {
      __pyx_1 = (__pyx_v_arc_dist <= __pyx_v_dmax);
    }
    if (__pyx_1) {

      /* "/opt/src/bpbio/seqfind/seqfind.pyx":224
 *             arc_dist = arc.distance
 *             if dmin <= arc_dist <= dmax:
 *                 self._find(arc, word, thresh, results)             # <<<<<<<<<<<<<< 
 * 
 */
      ((struct __pyx_vtabstruct_7seqfind_BKTree *)__pyx_v_self->__pyx_vtab)->_find(__pyx_v_self, __pyx_v_arc, __pyx_v_word, __pyx_v_thresh, __pyx_v_results);
      goto __pyx_L5;
    }
    __pyx_L5:;
  }
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_4);
  __Pyx_WriteUnraisable("seqfind.BKTree._find");
  __pyx_L0:;
  Py_DECREF(__pyx_v_arc);
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n___cinit__, "__cinit__"},
  {&__pyx_n___init__, "__init__"},
  {&__pyx_n___repr__, "__repr__"},
  {&__pyx_n_append, "append"},
  {&__pyx_n_edit_distance, "edit_distance"},
  {&__pyx_n_find, "find"},
  {0, 0}
};

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_k_1p, __pyx_k_1, sizeof(__pyx_k_1), 0},
  {0, 0, 0, 0}
};

static PyObject *__pyx_tp_new_7seqfind_Word(PyTypeObject *t, PyObject *a, PyObject *k) {
  struct __pyx_obj_7seqfind_Word *p;
  PyObject *o = (*t->tp_alloc)(t, 0);
  if (!o) return 0;
  p = ((struct __pyx_obj_7seqfind_Word *)o);
  p->info = Py_None; Py_INCREF(Py_None);
  if (__pyx_pf_7seqfind_4Word___cinit__(o, a, k) < 0) {
    Py_DECREF(o); o = 0;
  }
  return o;
}

static void __pyx_tp_dealloc_7seqfind_Word(PyObject *o) {
  struct __pyx_obj_7seqfind_Word *p = (struct __pyx_obj_7seqfind_Word *)o;
  Py_XDECREF(p->info);
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_7seqfind_Word(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_7seqfind_Word *p = (struct __pyx_obj_7seqfind_Word *)o;
  if (p->info) {
    e = (*v)(p->info, a); if (e) return e;
  }
  return 0;
}

static int __pyx_tp_clear_7seqfind_Word(PyObject *o) {
  struct __pyx_obj_7seqfind_Word *p = (struct __pyx_obj_7seqfind_Word *)o;
  PyObject* tmp;
  tmp = ((PyObject*)p->info);
  p->info = Py_None; Py_INCREF(Py_None);
  Py_XDECREF(tmp);
  return 0;
}

static struct PyMethodDef __pyx_methods_7seqfind_Word[] = {
  {"__repr__", (PyCFunction)__pyx_pf_7seqfind_4Word___repr__, METH_NOARGS|METH_COEXIST, 0},
  {0, 0, 0, 0}
};

static struct PyMemberDef __pyx_members_7seqfind_Word[] = {
  {"word", T_STRING, offsetof(struct __pyx_obj_7seqfind_Word, word), 0, 0},
  {"info", T_OBJECT, offsetof(struct __pyx_obj_7seqfind_Word, info), 0, 0},
  {"distance", T_INT, offsetof(struct __pyx_obj_7seqfind_Word, distance), 0, 0},
  {0, 0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_Word = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_Word = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_Word = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_Word = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_7seqfind_Word = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "seqfind.Word", /*tp_name*/
  sizeof(struct __pyx_obj_7seqfind_Word), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_7seqfind_Word, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  __pyx_pf_7seqfind_4Word___repr__, /*tp_repr*/
  &__pyx_tp_as_number_Word, /*tp_as_number*/
  &__pyx_tp_as_sequence_Word, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_Word, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_Word, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_7seqfind_Word, /*tp_traverse*/
  __pyx_tp_clear_7seqfind_Word, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_7seqfind_Word, /*tp_methods*/
  __pyx_members_7seqfind_Word, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  0, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_7seqfind_Word, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};
static struct __pyx_vtabstruct_7seqfind_BKTree __pyx_vtable_7seqfind_BKTree;

static PyObject *__pyx_tp_new_7seqfind_BKTree(PyTypeObject *t, PyObject *a, PyObject *k) {
  struct __pyx_obj_7seqfind_BKTree *p;
  PyObject *o = (*t->tp_alloc)(t, 0);
  if (!o) return 0;
  p = ((struct __pyx_obj_7seqfind_BKTree *)o);
  *(struct __pyx_vtabstruct_7seqfind_BKTree **)&p->__pyx_vtab = __pyx_vtabptr_7seqfind_BKTree;
  p->root = ((struct __pyx_obj_7seqfind_Word *)Py_None); Py_INCREF(Py_None);
  p->nodes = Py_None; Py_INCREF(Py_None);
  return o;
}

static void __pyx_tp_dealloc_7seqfind_BKTree(PyObject *o) {
  struct __pyx_obj_7seqfind_BKTree *p = (struct __pyx_obj_7seqfind_BKTree *)o;
  Py_XDECREF(((PyObject *)p->root));
  Py_XDECREF(p->nodes);
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_7seqfind_BKTree(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_7seqfind_BKTree *p = (struct __pyx_obj_7seqfind_BKTree *)o;
  if (p->root) {
    e = (*v)(((PyObject*)p->root), a); if (e) return e;
  }
  if (p->nodes) {
    e = (*v)(p->nodes, a); if (e) return e;
  }
  return 0;
}

static int __pyx_tp_clear_7seqfind_BKTree(PyObject *o) {
  struct __pyx_obj_7seqfind_BKTree *p = (struct __pyx_obj_7seqfind_BKTree *)o;
  PyObject* tmp;
  tmp = ((PyObject*)p->root);
  p->root = ((struct __pyx_obj_7seqfind_Word *)Py_None); Py_INCREF(Py_None);
  Py_XDECREF(tmp);
  tmp = ((PyObject*)p->nodes);
  p->nodes = Py_None; Py_INCREF(Py_None);
  Py_XDECREF(tmp);
  return 0;
}

static struct PyMethodDef __pyx_methods_7seqfind_BKTree[] = {
  {"find", (PyCFunction)__pyx_pf_7seqfind_6BKTree_find, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static struct PyMemberDef __pyx_members_7seqfind_BKTree[] = {
  {"nodes", T_OBJECT, offsetof(struct __pyx_obj_7seqfind_BKTree, nodes), 0, 0},
  {0, 0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_BKTree = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_BKTree = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_BKTree = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_BKTree = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_7seqfind_BKTree = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "seqfind.BKTree", /*tp_name*/
  sizeof(struct __pyx_obj_7seqfind_BKTree), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_7seqfind_BKTree, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_BKTree, /*tp_as_number*/
  &__pyx_tp_as_sequence_BKTree, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_BKTree, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_BKTree, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  "\n    a simple http://en.wikipedia.org/wiki/BK-tree\n    see tests for example usage.\n    takes a list of words and creates a tree that can be searched\n    quickly.  search with tree.find(\"word\", distance)\n\n    follows bearophiles code from here:\n    http://aspn.activestate.com/ASPN/Cookbook/Python/Recipe/572156\n\n        >>> words = (\"abcd\", \"def\", \"acdf\", \"gef\", \"wersdf\", \"asdfewd\"\n        ...        , \"sdfwe\", \"sdfwef\", \"kljd\", \"oiouoij\", \"ououoji\", \"ouonkoj\")\n\n        >>> tree = BKTree(words)\n        >>> for i in range(1, 4):\n        ...     i, tree.find(\"ddd\", i)\n        1 []\n        2 [\'def\']\n        3 [\'abcd\', \'def\', \'gef\', \'acdf\', \'kljd\']\n\n    the words can also be a Word() object. which takes the word to\n    compare, and any python object:\n\n        >>> words = [Word(\"asdf\", {\'info\':\"this is some info})\n        ...            , Word(\"asfd\", {\'zombies\': [24, \'g\']})]\n        >>> tree = BKTree(words)\n\n    this is useful for storing any info that goes with the object.\n        >>> f = tree.find(\"asdf, 0)\n        >>> f.info[\'info\']\n        \'zombies\'\n        >>> f.info[\'zombies\']\n        [24, \'g\']\n    ", /*tp_doc*/
  __pyx_tp_traverse_7seqfind_BKTree, /*tp_traverse*/
  __pyx_tp_clear_7seqfind_BKTree, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_7seqfind_BKTree, /*tp_methods*/
  __pyx_members_7seqfind_BKTree, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_pf_7seqfind_6BKTree___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_7seqfind_BKTree, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {"edit_distance", (PyCFunction)__pyx_pf_7seqfind_edit_distance, METH_VARARGS|METH_KEYWORDS, __pyx_doc_7seqfind_edit_distance},
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initseqfind(void); /*proto*/
PyMODINIT_FUNC initseqfind(void) {
  /*--- Libary function declarations ---*/
  __pyx_init_filenames();
  /*--- Module creation code ---*/
  __pyx_m = Py_InitModule4("seqfind", __pyx_methods, __pyx_mdoc, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1;};
  /*--- Intern code ---*/
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1;};
  /*--- String init code ---*/
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1;};
  /*--- Builtin init code ---*/
  __pyx_empty_tuple = PyTuple_New(0); if (unlikely(!__pyx_empty_tuple)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_skip_dispatch = 0;
  /*--- Global init code ---*/
  /*--- Function export code ---*/
  /*--- Type init code ---*/
  if (PyType_Ready(&__pyx_type_7seqfind_Word) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 116; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "Word", (PyObject *)&__pyx_type_7seqfind_Word) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 116; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_ptype_7seqfind_Word = &__pyx_type_7seqfind_Word;
  __pyx_vtabptr_7seqfind_BKTree = &__pyx_vtable_7seqfind_BKTree;
  *(void(**)(void))&__pyx_vtable_7seqfind_BKTree.addNode = (void(*)(void))__pyx_f_7seqfind_6BKTree_addNode;
  *(void(**)(void))&__pyx_vtable_7seqfind_BKTree.find = (void(*)(void))__pyx_f_7seqfind_6BKTree_find;
  *(void(**)(void))&__pyx_vtable_7seqfind_BKTree._find = (void(*)(void))__pyx_f_7seqfind_6BKTree__find;
  if (PyType_Ready(&__pyx_type_7seqfind_BKTree) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 128; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_SetVtable(__pyx_type_7seqfind_BKTree.tp_dict, __pyx_vtabptr_7seqfind_BKTree) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 128; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "BKTree", (PyObject *)&__pyx_type_7seqfind_BKTree) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 128; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_ptype_7seqfind_BKTree = &__pyx_type_7seqfind_BKTree;
  /*--- Type import code ---*/
  /*--- Function import code ---*/
  /*--- Execution code ---*/

  /* "/opt/src/bpbio/seqfind/seqfind.pyx":211
 *         return results
 * 
 *     cdef void _find(self, Word aroot, Word word, int thresh, results):             # <<<<<<<<<<<<<< 
 *         cdef int arc_dist, d = edit_distance(word.word, aroot.word, 1000)
 *         cdef int dmin = d - thresh
 */
  return;
  __pyx_L1:;
  __Pyx_AddTraceback("seqfind");
}

static char *__pyx_filenames[] = {
  "seqfind.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static INLINE void __Pyx_RaiseArgtupleTooLong(
    Py_ssize_t num_expected,
    Py_ssize_t num_found)
{
    const char* error_message =
    #if PY_VERSION_HEX < 0x02050000
        "function takes at most %d positional arguments (%d given)";
    #else
        "function takes at most %zd positional arguments (%zd given)";
    #endif
    PyErr_Format(PyExc_TypeError, error_message, num_expected, num_found);
}

static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type) {
    if (!type) {
        PyErr_Format(PyExc_SystemError, "Missing type object");
        return 0;
    }
    if (obj == Py_None || PyObject_TypeCheck(obj, type))
        return 1;
    PyErr_Format(PyExc_TypeError, "Cannot convert %s to %s",
        obj->ob_type->tp_name, type->tp_name);
    return 0;
}

static void __Pyx_WriteUnraisable(char *name) {
    PyObject *old_exc, *old_val, *old_tb;
    PyObject *ctx;
    PyErr_Fetch(&old_exc, &old_val, &old_tb);
    ctx = PyString_FromString(name);
    PyErr_Restore(old_exc, old_val, old_tb);
    if (!ctx)
        ctx = Py_None;
    PyErr_WriteUnraisable(ctx);
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        if (t->is_unicode) {
            *t->p = PyUnicode_DecodeUTF8(t->s, t->n - 1, NULL);
        } else {
            *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        }
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_SetVtable(PyObject *dict, void *vtable) {
    PyObject *pycobj = 0;
    int result;
    
    pycobj = PyCObject_FromVoidPtr(vtable, 0);
    if (!pycobj)
        goto bad;
    if (PyDict_SetItemString(dict, "__pyx_vtable__", pycobj) < 0)
        goto bad;
    result = 0;
    goto done;

bad:
    result = -1;
done:
    Py_XDECREF(pycobj);
    return result;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    if (__pyx_clineno) {
        py_funcname = PyString_FromFormat( "%s (%s:%u)", funcname, __pyx_cfilenm, __pyx_clineno);
    }
    else {
        py_funcname = PyString_FromString(funcname);
    }
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        __pyx_empty_tuple,  /*PyObject *consts,*/
        __pyx_empty_tuple,  /*PyObject *names,*/
        __pyx_empty_tuple,  /*PyObject *varnames,*/
        __pyx_empty_tuple,  /*PyObject *freevars,*/
        __pyx_empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}

/* Type Conversion Functions */

static INLINE Py_ssize_t __pyx_PyIndex_AsSsize_t(PyObject* b) {
  Py_ssize_t ival;
  PyObject* x = PyNumber_Index(b);
  if (!x) return -1;
  ival = PyInt_AsSsize_t(x);
  Py_DECREF(x);
  return ival;
}

static INLINE int __Pyx_PyObject_IsTrue(PyObject* x) {
   if (x == Py_True) return 1;
   else if (x == Py_False) return 0;
   else return PyObject_IsTrue(x);
}

static INLINE PY_LONG_LONG __pyx_PyInt_AsLongLong(PyObject* x) {
    if (PyInt_CheckExact(x)) {
        return PyInt_AS_LONG(x);
    }
    else if (PyLong_CheckExact(x)) {
        return PyLong_AsLongLong(x);
    }
    else {
        PY_LONG_LONG val;
        PyObject* tmp = PyNumber_Int(x); if (!tmp) return (PY_LONG_LONG)-1;
        val = __pyx_PyInt_AsLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE unsigned PY_LONG_LONG __pyx_PyInt_AsUnsignedLongLong(PyObject* x) {
    if (PyInt_CheckExact(x)) {
        long val = PyInt_AS_LONG(x);
        if (unlikely(val < 0)) {
            PyErr_SetString(PyExc_TypeError, "Negative assignment to unsigned type.");
            return (unsigned PY_LONG_LONG)-1;
        }
        return val;
    }
    else if (PyLong_CheckExact(x)) {
        return PyLong_AsUnsignedLongLong(x);
    }
    else {
        PY_LONG_LONG val;
        PyObject* tmp = PyNumber_Int(x); if (!tmp) return (PY_LONG_LONG)-1;
        val = __pyx_PyInt_AsUnsignedLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}


static INLINE unsigned char __pyx_PyInt_unsigned_char(PyObject* x) {
    if (sizeof(unsigned char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        unsigned char val = (unsigned char)long_val;
        if (unlikely((val != long_val)  || (long_val < 0))) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to unsigned char");
            return (unsigned char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE unsigned short __pyx_PyInt_unsigned_short(PyObject* x) {
    if (sizeof(unsigned short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        unsigned short val = (unsigned short)long_val;
        if (unlikely((val != long_val)  || (long_val < 0))) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to unsigned short");
            return (unsigned short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE char __pyx_PyInt_char(PyObject* x) {
    if (sizeof(char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        char val = (char)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to char");
            return (char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE short __pyx_PyInt_short(PyObject* x) {
    if (sizeof(short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        short val = (short)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to short");
            return (short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE int __pyx_PyInt_int(PyObject* x) {
    if (sizeof(int) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        int val = (int)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to int");
            return (int)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE long __pyx_PyInt_long(PyObject* x) {
    if (sizeof(long) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        long val = (long)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to long");
            return (long)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed char __pyx_PyInt_signed_char(PyObject* x) {
    if (sizeof(signed char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed char val = (signed char)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed char");
            return (signed char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed short __pyx_PyInt_signed_short(PyObject* x) {
    if (sizeof(signed short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed short val = (signed short)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed short");
            return (signed short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed int __pyx_PyInt_signed_int(PyObject* x) {
    if (sizeof(signed int) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed int val = (signed int)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed int");
            return (signed int)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed long __pyx_PyInt_signed_long(PyObject* x) {
    if (sizeof(signed long) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed long val = (signed long)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed long");
            return (signed long)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE long double __pyx_PyInt_long_double(PyObject* x) {
    if (sizeof(long double) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        long double val = (long double)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to long double");
            return (long double)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}
